(function(g){var window=this;var cAa=function(a,b,c,d){c=(0,g.z)(c,d||a.A);b=g.eH(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},dAa=function(a){a.o||(a.o=new g.lE,g.K(a,a.o));
return a.o},i2=function(a){a.U("cardstatechange",a.ce()&&a.se()?1:0)},hAa=function(a){var b=g.Th(a,"fontSize");
var c=(c=b.match(eAa))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.ce){if(String(c)in fAa)return g.ki(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in gAa)return a=a.parentNode,c=g.Th(a,"fontSize"),g.ki(a,b==c?"1em":b,"left","pixelLeft")}c=g.he("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.pe(c);return b},j2=function(a,b){this.start=a<b?a:b;
this.end=a<b?b:a},iAa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ql&&a.dataset){if(g.qc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Dc("pollChoiceIndex"))},m2=function(a){a=g.Ma(a);
delete k2[a];g.dc(k2)&&l2&&l2.stop()},kAa=function(){l2||(l2=new g.V(function(){jAa()},20));
var a=l2;a.isActive()||a.start()},jAa=function(){var a=(0,g.H)();
g.Mb(k2,function(b){lAa(b,a)});
g.dc(k2)||kAa()},mAa=function(a,b){g.Hf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},n2=function(a,b,c,d){g.Nu.call(this);
if(!g.Fa(a)||!g.Fa(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.G=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.F=0;this.B=null},lAa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;nAa(a,a.progress);1==a.progress?(a.o=0,m2(a),a.Hd(),a.Gn()):a.sb()&&a.Kw()},nAa=function(a,b){g.Ia(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.G[c]-a.A[c])*b+a.A[c]},o2=function(a,b,c,d,e){n2.call(this,b,c,d,e);
this.element=a},p2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
o2.call(this,a,b,c,d,e)},oAa=function(a){return Math.pow(a,3)},pAa=function(a){return 3*a*a-2*a*a*a},q2=function(a,b){(0,g.C)(b,function(b){g.XH("visualElementShown",{csn:a,
ve:g.fI(b),eventType:4},g.bI,void 0,void 0)})},r2=function(a,b){(0,g.C)(b,function(b){g.XH("visualElementHidden",{csn:a,
ve:g.fI(b),eventType:8},g.bI,void 0,void 0)})},s2=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Jd=b.session_data||{};this.C=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.A={KM:a.impression,click:a.click,close:a.close,WV:a.teaser_impression,Wx:a.teaser_click};b=b.tracking_params||{};this.F=g.eI(b.card);this.H=g.eI(b.teaser);this.D=g.eI(b.icon)},t2=function(a,b){g.ig.call(this);
this.Km=a;this.Fu=b;this[g.Mf]=!1},x2=function(a,b,c,d){t2.call(this,a,b);
a=this.Fu;b=this.ra();c?(b.setAttribute("stroke",c.o),b.setAttribute("stroke-opacity",1),c=c.ab(),g.u(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/qAa(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Fu;a=this.ra();if(d instanceof u2)a.setAttribute("fill",d.J),a.setAttribute("fill-opacity",d.K);else if(d instanceof v2){b="lg-"+d.D+"-"+d.G+"-"+d.F+"-"+d.H+"-"+d.o+"-"+d.A;var e=b in c.A?c.A[b]:null;if(!e){e=w2(c,"linearGradient",{x1:d.D,
y1:d.G,x2:d.F,y2:d.H,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.o;g.Ba(d.C)&&(f+=";stop-opacity:"+d.C);f=w2(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.A;g.Ba(d.B)&&(f+=";stop-opacity:"+d.B);d=w2(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=rAa(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},sAa=function(){},tAa=function(a,b){t2.call(this,a,b)},y2=function(){this.ub=[];
this.Pa=[];this.Ie=[]},z2=function(a,b,c,d){var e=a.fe[0]-b*Math.cos(g.Md(d))+b*Math.cos(g.Md(d+90)),f=a.fe[1]-c*Math.sin(g.Md(d))+c*Math.sin(g.Md(d+90));
a.ub.push(3);a.Pa.push(1);a.Ie.push(b,c,d,90,e,f);a.Wn=!1;a.fe=[e,f]},vAa=function(a,b){for(var c=a.Ie,d=0,e=0,f=a.ub.length;e<f;e++){var k=a.ub[e],l=uAa[k]*a.Pa[e];
b(k,c.slice(d,d+l));d+=l}},wAa=function(a,b,c,d){x2.call(this,a,b,c,d)},A2=function(a,b){this.A=a;
this.o=b},B2=function(a,b,c,d,e){g.kw.call(this,e);
this.width=a;this.height=b;this.B=c||null;this.M=d||null},qAa=function(a){var b=a.Zj();
return b?b.width/(a.B?new g.Pd(a.B,a.M):a.Zj()).width:0},xAa=function(a,b){t2.call(this,a,b)},v2=function(a,b,c,d,e,f,k,l){this.D=a;
this.G=b;this.F=c;this.H=d;this.o=e;this.A=f;this.C=g.za(k)?k:null;this.B=g.za(l)?l:null},u2=function(a,b){this.J=a;
this.K=null==b?1:b},C2=function(a,b){t2.call(this,a,b)},yAa=function(a,b,c,d){x2.call(this,a,b,c,d)},D2=function(a,b){t2.call(this,a,b)},E2=function(a,b,c,d,e){B2.call(this,a,b,c,d,e);
this.A={};this.V=g.ee&&!g.Lc(526);this.K=new g.Xn(this)},w2=function(a,b,c){a=a.J.o.createElementNS("http://www.w3.org/2000/svg",b);
c&&F2(a,c);return a},F2=function(a,b){for(var c in b)a.setAttribute(c,b[c])},G2=function(a,b,c,d){b=w2(a,"path",{d:zAa(b)});
c=new yAa(b,a,c,d);a.C.ra().appendChild(c.ra())},zAa=function(a){var b=[];
vAa(a,function(a,d){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var c=d[3];b.push("A",d[0],d[1],0,180<Math.abs(c)?1:0,0<c?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},rAa=function(a,b,c){if(b in a.A)return a.A[b];
var d="_svgdef_"+AAa++;c.setAttribute("id",d);a.A[b]=d;a.H.appendChild(c);return d},BAa=function(){H2||(H2=new g.Tg(400),H2.start());
return H2},I2=function(a,b){function c(a){return a.baseUrl}
function d(a){if(a){var b=a.simpleText;if(b)return b;if(a.runs)return(0,g.I)(a.runs,function(a){return a.text}).join("")}}
function e(a){if(a){var b=[],c=a.videoId;c&&b.push("v="+c);(c=a.playlistId)&&b.push("list="+c);(a=a.startTimeSeconds)&&b.push("t="+a);return"/watch?"+b.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.I)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.eI(a.trackingParams));var k=(0,g.I)(a.elements||[],function(a,f){var k=a.endscreenElementRenderer;if(!k)return null;var l={},m=k.style,v=k.endpoint||{};l.id="element-"+f;l.type=m;l.title=d(k.title);l.metadata=d(k.metadata);l.callToAction=d(k.callToAction);l.ZA=k.image;l.left=parseFloat(k.left);l.width=parseFloat(k.width);l.top=parseFloat(k.top);l.aspectRatio=
parseFloat(k.aspectRatio);l.startMs=parseInt(k.startMs,10);l.endMs=parseInt(k.endMs,10);l.clickUrls=(0,g.I)(v.loggingUrls||[],c);l.Eo=g.Wb(k,"title","accessibility","accessibilityData","label");l.impressionUrls=(0,g.I)(k.impressionUrls||[],c);l.XL=(0,g.I)(k.hovercardShowUrls||[],c);l.Jd={itct:k.trackingParams};l.visualElement=g.eI(k.trackingParams);if("VIDEO"==m)l.targetUrl=v.urlEndpoint?v.urlEndpoint.url:e(v.watchEndpoint),l.Wp=!1,l.Nr=b,l.videoDuration=d(k.videoDuration);else if("PLAYLIST"==m)l.targetUrl=
v.urlEndpoint?v.urlEndpoint.url:e(v.watchEndpoint),l.Wp=!1,l.Nr=b,l.playlistLength=d(k.playlistLength);else if("CHANNEL"==m){if(m=g.Wb(v,"browseEndpoint","browseId"))l.channelId=m,l.targetUrl="/channel/"+m;l.Wp=!1;l.Nr="new";l.isSubscribe=!!k.isSubscribe;if(l.isSubscribe){a:{if(m=k.hovercardButton)if(m=m.subscribeButtonRenderer){v=d(m.unsubscribedButtonText);var A=d(m.subscribedButtonText);if(m.subscribed){var E=d(m.subscriberCountWithUnsubscribeText);var G=d(m.subscriberCountText)}else E=d(m.subscriberCountText),
G=d(m.subscriberCountWithSubscribeText);var M=null;if(k.signinEndpoint&&(M=g.Wb(k,"signinEndpoint","webNavigationEndpointData","url"),!M)){k=void 0;break a}if(v&&(A||M)){k={subscribed:m.subscribed,subscribeText:v,subscribeCount:E,unsubscribeText:A,unsubscribeCount:G,enabled:m.enabled,signinUrl:M,classic:k.useClassicSubscribeButton};break a}}k=void 0}l.subscribeButton=k}else l.subscribersText=d(k.subscribersText)}else"WEBSITE"==m&&(l.targetUrl=g.Wb(v,"urlEndpoint","url"),l.Wp=!0,l.Nr="new",l.iconUrl=
k.icon.thumbnails[0].url);return l});
f.elements=(0,g.qe)(k,function(a){return!!a});
return f},J2=function(a){g.lV.call(this,a);
this.A=null;this.K=!1;this.B=null;this.o={};this.G={};this.F=this.C=null;this.L=[];a=g.Y(a);this.M=g.RN(a)||g.SN(a);this.wG=!0;this.H=0;this.J=new g.lq(null);this.D=new g.jH(this);g.K(this,this.D);this.D.R(this.player,g.nR("creatorendscreen"),this.GN);this.D.R(this.player,"crx_creatorendscreen",this.HN);this.D.R(this.player,"resize",this.kD);this.D.R(window,"focus",this.HU);this.load();var b=g.je("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ef(this,function(){g.pe(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},CAa=function(a){return a.player.getVideoData().Jc?"current":a.M?"new":"current"},K2=function(a){return"creator-endscreen-editor"===a},L2=function(a,b){g.aV(a.player,"creatorendscreen");
a.C&&(a.C.dispose(),a.C=null,a.F.dispose(),a.F=null);for(var c in a.o)a.o[c].dispose();a.o={};a.G={};0<a.L.length&&(a.L.forEach(function(a){a.dispose()}),a.L.length=0);
a.H=0;if((a.A=b)&&b.elements){DAa(a);c=[];var d=new g.lR(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.Y(a.player).A||(a.C=new g.W({I:"div",N:"ytp-ce-shadow"}),g.cV(a.player,a.C.element,4),a.F=new g.JV(a.C,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=EAa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.cV(a.player,f.element,4);var k=new g.lR(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);FAa(a,f,e)}g.YU(a.player,
c);a.kD()}},DAa=function(a){var b=g.uI(),c=g.vI();
c&&b&&a.A.visualElement&&g.gI(c,b,[a.A.visualElement],void 0)},EAa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={I:"div",da:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.Eo||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",T:M2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",T:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",da:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],T:{dir:g.mq(a.J,b.title||"")},ca:b.title},{I:"div",N:"ytp-ce-video-duration",ca:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={I:"div",da:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.Eo||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",T:M2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",T:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",da:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],T:{dir:g.mq(a.J,b.title||"")},ca:b.title},{I:"div",N:"ytp-ce-playlist-count",P:[{I:"div",
N:"ytp-ce-playlist-icon"},{I:"div",N:"ytp-ce-playlist-count-text",ca:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={I:"div",da:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.Eo||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",P:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",
P:[{I:"div",N:"ytp-ce-expanding-overlay-body",P:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",P:[{I:"a",da:["ytp-ce-channel-title","ytp-ce-link"],T:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.mq(a.J,b.title||"")},ca:b.title},b.subscribeButton?{I:"div",N:"ytp-ce-subscribe-container",P:[{I:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",N:"ytp-ce-channel-subscribers-text",ca:b.subscribersText}:"",b.metadata?{I:"div",da:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ca:b.metadata}:""]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",T:M2(b)}]};c=new g.W(c);var d=g.Wd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.S(d,"ytp-ce-subscribe-button");if(g.Y(a.player).A){var e=null;var f=b.Jd.itct}else e="endscreen",f=null;e=new g.y_(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.L.push(e)}break;case "WEBSITE":c={I:"div",da:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.Eo||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",P:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",P:[{I:"div",N:"ytp-ce-expanding-overlay-body",
P:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",P:[{I:"div",N:"ytp-ce-website-title",T:{dir:g.mq(a.J,b.title||"")},ca:b.title},{I:"div",N:"ytp-ce-website-metadata",ca:b.metadata},{I:"a",da:["ytp-ce-website-goto","ytp-ce-link"],T:{href:b.targetUrl,target:"_blank",tabindex:"-1"},ca:b.callToAction}]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",T:M2(b)},{I:"div",N:"ytp-ce-expanding-icon",T:GAa(b.iconUrl)}]},c=new g.W(c)}b.o&&g.S(c.element,"ytp-ce-placeholder");return c},M2=function(a){if(a.ZA)var b=
a.ZA.thumbnails;
return GAa(b?b[b.length-1].url:null)},GAa=function(a){return a?{style:"background-image: url("+a+")"}:{}},FAa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.X("mouseenter",(0,g.z)(a.dw,a,b,c));b.X("mouseleave",(0,g.z)(a.Sw,a,b,c));g.Y(a.player).A||b.X("click",(0,g.z)(function(a){g.S(a.element,"ytp-ce-element-hover")},a,b));
b.X("click",(0,g.z)(a.DE,a,c));b.X("keypress",(0,g.z)(a.DE,a,c));b.X("focus",(0,g.z)(function(a,b){this.dw(a,b)},a,b,c));
b.X("blur",(0,g.z)(function(a,b){this.Sw(a,b)},a,b,c));
b.X("touchstart",(0,g.z)(a.dw,a,b,c));var f=g.Yd("ytp-ce-expanding-overlay-hider",b.element);f&&b.R(f,"touchstart",function(a){a=a||window.event;a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation();g.Br(b.element,"ytp-ce-element-hover");g.Br(b.element,"ytp-ce-force-expand")});
b.X("keydown",(0,g.z)(function(a,b){this.wG=9==b.keyCode&&!b.shiftKey},a,b));
var k=(0,g.z)(function(a,b,c){this.H+=c;0<this.H?(g.S(a.element,"ytp-ce-force-expand"),N2(this,b.id,!0)):(g.Br(a.element,"ytp-ce-force-expand"),g.Br(a.element,"ytp-ce-element-hover"),N2(this,b.id,!1))},a,b,c);
a=(0,g.z)(function(a,b){b&&(a.X("blur",function(){g.ji(b)&&this.wG&&b.focus()}),a.R(b,"focus",d),a.R(b,"blur",e))},a,b);
a(g.Yd("ytp-sb-subscribe",b.element));a(g.Yd("ytp-sb-unsubscribe",b.element));b.X("focus",d);b.X("blur",e)},N2=function(a,b,c){a.C&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.T(a.o[d].element,"ytp-ce-element-shadow-show",c)},O2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||K2(g.Y(a.player).playerStyle))c&&c();else{b=HAa(a,b);var e=0,f=!1,k=new g.V(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.pG(b[a],d)}},P2=function(a,b,c){O2(a,b.clickUrls,c);
(a=g.vI())&&b.Wp&&g.iI(a,b.visualElement)},HAa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(IAa(b[e],c));return d},IAa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(a){var c=unescape(a);
c=c.substring(1,c.length-1);return b[c]?escape(b[c]):a})},Q2=function(a){return g.Fa(a)&&a.length?a[0]:a},R2=function(a){var b=/.+/;
return g.u(a)&&null!=b&&null!=a&&a.match(b)?a:""},S2=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},T2=function(a){return g.u(a)?a:""},U2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},V2=function(a,b){return"true"==a||"false"==a?"true"==a:b},W2=function(a,b){return g.u(a)?parseFloat(a):b},X2=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Hd(a,b,c);if(a>=b&&a<=c)return a}return e},JAa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.C)(a,function(a){a=parseFloat(a);0>a&&(c=-c);b=60*b+Math.abs(a)});
return c*b},Y2=function(a,b){if(null==a)return null;
if(g.Ha(a)){var c=[];(0,g.C)(a,function(a){(a=b(a))&&c.push(a)});
return c}var d=b(a);return d?[d]:[]},KAa=function(a){function b(a){return null!=a&&!isNaN(a)}
return(a=a?new g.yh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},LAa=function(a){function b(a){return(0,g.qe)(a.split(/ +/),function(a){return""!=a})}
return null==a?[]:b(a)},MAa=function(a){this.externalId=a},NAa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},Z2=function(a){if(!a)return null;
var b=g.hd(T2(a.value));b=g.ed(b);if(!b)return null;var c=U2(a.target,OAa,"current");return null==c?null:new NAa(b,c,V2(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},$2=function(a){return a.value?a.value:null},PAa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},SAa=function(a){if(!a)return null;
var b=U2(a.type,QAa),c=U2(a.trigger,RAa),d=Q2(a.url);d=Z2(d?d:null);a=Q2(a.subscribeData);var e=a?a:null;e?(a=T2(e.external_user_id),e=T2(e.subscription_token),a=a&&e?new MAa(a):null):a=null;return b?new PAa(b,c,d,a):null},TAa=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},a3=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},b3=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.zl=c;this.C=d;this.t=e;this.D=f;this.F=k;this.G=l;this.B=m;this.A=n;this.o=p},VAa=function(a,b){if(!a)return null;
var c=W2(a.x,0),d=W2(a.y,0),e=W2(a.w,0),f=W2(a.h,0),k=JAa(a.t),l=W2(a.d,0),m=W2(a.px,0),n=W2(a.py,0),p=W2(a.scaleSlope,1),t=W2(a.scaleSlopeX,p);p=W2(a.scaleSlopeY,p);var v=U2(a.scaleDimension,UAa,"xy");return b(c,d,e,f,k,l,m,n,t,p,v)},c3=function(a,b){var c=WAa(b,XAa(a,new g.Bh(a.x,a.y,a.zl,a.C),b.o)),d=b.o,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Hd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Hd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},XAa=function(a,b,c){var d=a.F,e=a.G,f=a.o?a.o:"xy",k=TAa(c,a.B,f);
a=a3(c,a.A,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.Bh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},YAa=function(a){return a?VAa(a,function(a,c,d,e,f,k,l,m,n,p,t){return new b3(a,c,d,e,f,k,l,m,n,p,t)}):null},ZAa=function(a,b){this.o=a;
this.A=b||null},WAa=function(a,b){var c=a.A?c3(a.A,new ZAa(a.o)):a.o;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.Nd?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ba(c)&&(d.top+=c));return d},$Aa=function(a,b,c,d,e,f,k,l,m,n,p,t,v){b3.call(this,a,b,c,d,e,l,m,n,p,t,v);
this.H=f;this.J=k},aBa=function(a){if(!a)return null;
var b=W2(a.sx,0),c=W2(a.sy,0);return VAa(a,function(a,e,f,k,l,m,n,p,t,v,A){return new $Aa(a,e,f,k,l,b,c,m,n,p,t,v,A)})},bBa=function(a,b,c,d,e,f,k,l,m,n,p,t,v,A){this.A=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.o=e;this.F=f;this.C=k;this.textAlign=l;this.textSize=m;this.B=n;this.padding=p;this.effects=t;this.cornerRadius=v;this.D=A},dBa=function(a){if(!a)return null;
var b=S2(a.fgColor,"#1A1A1A"),c=S2(a.bgColor,"#FFF"),d=S2(a.borderColor,"#000"),e=X2(a.borderWidth,0,5,!1,0),f=X2(a.bgAlpha,0,1,!1,.8),k=S2(a.highlightFontColor,"#F2F2F2"),l=X2(a.highlightWidth,0,5,!1,3),m=T2(a.textAlign),n=X2(a.textSize,3.3,30.1,!0,3.6107),p=T2(a.fontWeight),t=KAa(a.padding),v=LAa(a.effects),A=X2(a.cornerRadius,0,10,!0,0);a=Q2(a.gradient);if(a=a?a:null){var E=X2(a.x1,0,100,!0,0),G=X2(a.y1,0,100,!0,0),M=X2(a.x2,0,100,!0,100),U=X2(a.y2,0,100,!0,100),La=S2(a.color1,"#FFF"),ib=S2(a.color2,
"#000");a=new cBa(E,G,M,U,La,ib,X2(a.opacity1,0,100,!0,100),X2(a.opacity2,0,100,!0,0))}else a=null;return new bBa(b,c,d,e,f,k,l,m,n,p,t,v,A,a)},cBa=function(a,b,c,d,e,f,k,l){this.C=a;
this.D=b;this.B=c;this.F=d;this.o=e;this.A=f;this.G=k;this.H=l},eBa=function(a,b,c,d){this.type=a;
this.A=b;this.o=c;this.C=d},gBa=function(a){if(!a)return null;
var b=U2(a.type,fBa,"rect"),c=Y2(a.rectRegion,YAa),d=Y2(a.anchoredRegion,aBa);a=Y2(a.shapelessRegion,YAa);return new eBa(b,c,d,a)},hBa=function(a){return a.A&&a.A.length?a.A[0]:a.o&&a.o.length?a.o[0]:a.C&&a.C.length?a.C[0]:null},iBa=function(a,b){this.A=a;
this.o=b},jBa=function(a,b){this.state=a;
this.ref=b},lBa=function(a){if(!a)return null;
var b=U2(a.state,kBa);a=R2(a.ref);return b?new jBa(b,a):null},mBa=function(a,b,c,d){this.o=a||[];
this.C=b||[];this.B=c;this.A=d;this.value=!1},nBa=function(a){if(!a)return null;
var b=Y2(a.condition,lBa),c=Y2(a.notCondition,lBa),d=V2(a.show_delay,!1);a=V2(a.hide_delay,!1);return b||c?new mBa(b,c,d,a):null},oBa=function(a,b,c){(0,g.C)(a.o,g.Na(b,!1),c);
(0,g.C)(a.C,g.Na(b,!0),c)},d3=function(a,b,c,d,e,f,k,l,m,n,p,t,v,A){this.id=a;
this.author=b;this.type=c;this.style=d;this.B=e;this.segment=f;this.C=k||[];this.G=l||[];this.A=m;this.F=n;this.D=p;this.data=t;this.o=v;this.itct=A},rBa=function(a){if(!a)return null;
var b=R2(a.id),c=R2(a.author),d=U2(a.type,pBa),e=U2(a.style,e3),f=T2(Q2(a.TEXT)),k=T2(a.data);k=0!=k.length?JSON.parse(k):{};var l=Q2(a.segment);var m=l?l:null;m?(R2(m.timeRelative),l=R2(m.spaceRelative),l=(m=Y2(m.movingRegion,gBa))?new iBa(l,m):null):l=null;m=Y2(a.action,SAa);var n=Y2(a.trigger,nBa),p=Q2(a.appearance);(p=dBa(p?p:null))||(p=dBa({}));var t=U2(a.coordinate_system,qBa,"video_relative"),v=V2(a.closeable,!0),A=T2(a.log_data);a=T2(a.itct);return b&&d?new d3(b,c,d,e,f,l,m,n,p,t,v,k,A,a):
null},g3=function(a){return f3(a,function(a){return"click"==a.trigger})},f3=function(a,b){return(0,g.yk)(a.C,b,void 0)},sBa=function(a,b,c){(0,g.C)(a.C,b,c)},tBa=function(a,b){return g.Ta(a.C,b,void 0)},uBa=function(a,b,c){(0,g.C)(a.G,b,c)},vBa=function(a,b){(0,g.I)(a.G,b,void 0)},h3=function(a){return(a=wBa(a))?hBa(a):null},wBa=function(a){a.segment?(a=a.segment,a=a.o.length?a.o[0]:null):a=null;
return a},xBa=function(a,b){var c=h3(a);
return c&&b?a3(b,c.A,c.o?c.o:"xy"):1},zBa=function(a,b,c){this.o={};
this.C=!1;this.D="ivTrigger:"+a;this.A=c;oBa(b,function(a,b){var c=yBa(b.state,b.ref);this.A.subscribe(c,(0,g.z)(this.B,this,c,a));this.o[c]=a},this)},yBa=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},i3=function(){this.o=!1;
this.D=this.A=null},j3=function(a,b,c){a.A?(a.A.setSize(b,c),a.A.clear()):(b=new E2(b,c,void 0,void 0,void 0),a.A=b,a.A.Gp(),a.D=g.he("DIV"),b=a.A.ra(),a.D.appendChild(b));
return a.A},k3=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Mb(b,function(a,b){d.setAttribute(b,a)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},l3=function(a,b){var c=":"+(g.jw.getInstance().o++).toString(36);
b.setAttribute("result",c);a.appendChild(b);return c},ABa=function(a,b){var c=l3(a,k3("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=l3(a,k3("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},k3("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=l3(a,k3("feComposite",{"in":c,in2:b,operator:"in"}));return l3(a,k3("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},BBa=function(a,b){var c=l3(a,k3("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=l3(a,k3("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=l3(a,k3("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=l3(a,k3("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=l3(a,k3("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=l3(a,k3("feComposite",{operator:"out","in":c,in2:d}));return l3(a,k3("feComposite",{operator:"over","in":b,in2:c}))},CBa=function(a,b){return b},DBa=function(a){var b=
k3("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.C)(a,function(a){a:{switch(a){case "bevel":a=ABa;break a;case "dropshadow":a=BBa;break a}a=CBa}c=a(b,c)});
return b},EBa=function(a){a=(0,g.qe)(a,function(a){return a in m3});
g.tb(a,function(a,c){return m3[a]-m3[c]});
return a},FBa=function(a){return g.Ta(a,function(a){return"dropshadow"==a})?new g.yh(0,7,7,0):new g.yh(0,0,0,0)},GBa=function(a,b,c){var d=new y2;
d.moveTo(a.left+b+c,a.top+c);d.Ic(a.left+a.width-b-c,a.top+c);z2(d,b,b,-90);d.Ic(a.left+a.width-c,a.top+a.height-b-c);z2(d,b,b,0);d.Ic(a.left+b+c,a.top+a.height-c);z2(d,b,b,90);d.Ic(a.left+c,a.top+b+c);z2(d,b,b,180);d.close();return d},HBa=function(a,b,c,d){var e=a.D;
e?a=new v2(e.C*b/100,e.D*c/100,e.B*b/100,e.F*c/100,e.o,e.A,e.G,e.H):(b=a.o,a=new u2(a.bgColor,d?Math.max(b,.9):b));return a},n3=function(a,b){var c=g.Ch(a);
c.expand(FBa(b));return new g.Bh(c.left,c.top,c.right-c.left,c.bottom-c.top)},IBa=function(a,b,c){if(c.length&&(b=g.Wd(document,"g",void 0,b),b.length)){var d=EBa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.A?a.A[c]:null;e?a=e:(d=DBa(d),a=0<d.childNodes.length?rAa(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},o3=function(){i3.call(this);
this.B=0},JBa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},p3=function(a){i3.apply(this,arguments)},q3=function(a){i3.apply(this,arguments)},r3=function(a){o3.apply(this,arguments)},s3=function(a,b,c,d,e){g.J.call(this);
this.o=a;this.Y=b;this.F=c;this.ea=d;this.ga=e;this.J=!1;this.Z=new g.gH(this);g.K(this,this.Z);this.V=this.D=this.G=this.M=this.A=null;this.aa=!1;this.ba=this.K=this.L=null;this.Jq=new g.km(this.rL,100,this);g.K(this,this.Jq);this.H=new g.V(this.gC,500,this);g.K(this,this.H);this.O=this.C=this.B=null},KBa=function(a,b){var c=(0,g.z)(function(a,c,f){c=f?t3(this,c,(0,g.z)(f,this)):t3(this,c);
this.Z.X(b,a,c)},a);
c("mouseover","G",a.tD);c("mouseout","F",a.Uh);c("click","D");c("touchend","D")},LBa=function(a){if(a.o.D){if(f3(a.o,function(a){return"close"==a.type}))var b=a.A;
else a.B=g.he("DIV","annotation-close-button"),g.L(a.B,!1),g.dF(a.B,"annotation_id",a.o.id),a.A.appendChild(a.B),b=a.B;var c=function(a){a.stopPropagation()};
a.Z.X(b,"click",t3(a,"E",c));a.Z.X(b,"touchend",t3(a,"E",c))}},t3=function(a,b,c){return(0,g.z)(function(a){if(this.ga)c&&c(a);
else if(a.event.target instanceof Element){var d=a.event.target;g.L(d,!1);try{var f=document.elementFromPoint(a.event.clientX,a.event.clientY);if(g.Ee(f,"annotation")){var k=document.createEvent("MouseEvent");k.initMouseEvent(a.event.type,a.event.bubbles,a.event.cancelable,a.event.view,a.event.detail,a.event.screenX,a.event.screenY,a.event.clientX,a.event.clientY,a.event.ctrlKey,a.event.altKey,a.event.shiftKey,a.event.metaKey,a.event.button,a.event.relatedTarget);f.dispatchEvent(k)}}finally{g.L(d,
!0)}}d=g.hi(a.target);a=new g.Nd(a.clientX,a.clientY);"F"==b&&d.contains(a)||this.ea.U(b,this.o)},a)},v3=function(a){if(a.A||a.C){var b=h3(a.o);
if(b){var c=u3(a);if(a.A){b=c3(b,c);var d=g.PU(a.F).getVideoContentRect();g.fi(a.A,b.width,b.height);g.Vh(a.A,b.left,b.top);a.M=new g.Bh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=h3(a.o))&&d?TAa(d,e.B,e.o?e.o:"xy"):1;var f=xBa(a.o,d);d=a.o.A;d.padding?d=d.padding:(d="speech"==a.o.style?1.6:.8,d=new g.yh(d,d,d,d));d=new g.yh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.D&&(d.right+=1.5*c.o.height/100);a.A.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+
d.left+"px";"label"==a.o.style&&a.G&&(a.G.style.padding=a.A.style.padding);d=c.o;var k=!1,l=0,m=0;var n=g.PU(a.F).getVideoContentRect();var p=g.WU(a.F);g.Dh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.o.F&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.D){f=MBa(a,23,b,d,e);if(a.B){var t=43-f.width;0<t&&(b.left+f.left-t>n.left&&(f.left-=t),f.width+=t)}t=f;g.fi(a.D,f.width,f.height);g.Vh(a.D,f.left,f.top)}a.B&&
(t?b=new g.Nd(t.left+t.width-23-18,a.aa?t.top+2:t.top+t.height-18-2):(t=MBa(a,18,b,d,e),b=new g.Nd(t.left,t.top),g.fi(a.B,t.width,t.height)),g.Vh(a.B,b));a.V=new g.Bh(a.M.left+t.left,a.M.top+t.top,t.width,t.height);a.L=a.Z.X(g.PU(a.F),"mousemove",a.wO,a)}else a.D&&(t=e/f*d.height*4.2/100,t=new g.Pd(t,t),"highlight"==a.o.type||"label"==a.o.style?(e=1.5*d.height/100,t=new g.Bh(b.width-t.width-e,b.height-t.height-e,t.width,t.height)):t=new g.Bh(b.width-t.width-3*d.height/100,(b.height-t.height)/2,t.width,
t.height),g.fi(a.D,t.width,t.height),g.Vh(a.D,t.left,t.top)),a.B&&(t=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Vh(a.B,t&&e?new g.Nd(b.width-9,-9):t?new g.Nd(b.width-9,45<b.height?9:b.height-9):e?new g.Nd(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.Nd(45<b.width?b.width-9-18:-9,b.height-9):new g.Nd(-9,45<b.height?9:b.height-9)))}a.C&&a.C.C(a.o,c);if(a.A){c=a.A;b=a.o.A;c.style.color="highlightText"==a.o.style?b.F:b.A;t=g.PU(a.F).getVideoContentRect();c.style.fontSize=
360*b.textSize*xBa(a.o,t)/100+"px";t=a.o.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==t||"highlightText"==t?"center":"left";b.B&&(c.style.fontWeight=b.B);a=a.A;c=a.style.overflow;t=(b=g.Yd("annotation-link-icon",a))?g.ji(b):!1;e=(d=g.Yd("annotation-close-button",a))?g.ji(d):!1;t&&g.L(b,!1);e&&g.L(d,!1);m=f="";if(n=g.Yd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>
a.offsetWidth){l=k=hAa(a);p=5;for(var v=Math.floor(k/2);v;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+v,k)):l=Math.max(l-v,p),v=Math.floor(v/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.L(d,!0);t&&g.L(b,!0)}}}},MBa=function(a,b,c,d,e){var f=0<e;
b=new g.Bh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.S(a.A,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.S(a.A,"annotation-extend-up"),a.aa=!0);return b},w3=function(a){return"label"!=a.o.style||a.C.o},u3=function(a){var b=g.PU(a.F).getVideoContentRect();
if("player_relative"==a.o.F){var c=g.PU(a.F).getPlayerSize();b=new g.Bh(-b.left,-b.top,c.width,c.height)}else b=new g.Bh(0,0,b.width,b.height);return new ZAa(b,a.O?h3(a.O):null)},NBa=function(a,b){return b?new g.Bh(a.x+b.left,a.y+b.top,b.width,b.height):null},x3=function(a,b,c){g.J.call(this);
this.A=a;this.annotation=b;this.view=c;this.o=null;this.C=this.isVisible=!1;OBa(b,a)},OBa=function(a,b){vBa(a,function(c){return new zBa(a.id,c,b)})},PBa=function(a){a.A.unsubscribe("resize",a.sD,a);
a.A.unsubscribe("onVideoAreaChange",a.iF,a)},y3=function(a){a.o&&(a.o.stop(),a.o=null)},QBa=function(a,b,c){s2.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=Z2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},z3=function(a,b,c){s2.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.B=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=Z2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.o=null;if(a=b.signin_url)this.o=Z2({target:"current",value:a});this.L=b.signin_title||null;this.K=b.signin_message||null},RBa=function(a,b,c){z3.call(this,a,b,c);
this.J=b.ypc_flow_type;this.G=b.innertube_request_params},SBa=function(a,b,c){s2.call(this,a,b,c);
this.B=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=Z2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},TBa=function(a,b,c){s2.call(this,a,b,c);
this.G=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.o=b.hasOwnProperty("old_vote")?b.old_vote:null;this.B=null;if(a=b.signin_url)this.B=Z2({target:"current",value:a});this.J=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},VBa=function(a,b,c){z3.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new UBa(a[b]))},UBa=function(a){this.merchant=g.F(a.merchant);
this.price=g.F(a.price)},WBa=function(a,b,c){z3.call(this,a,b,c);
this.M=b.ypc_item_type;this.J=b.ypc_item_id;this.G=b.ypc_flow_type},XBa=function(a,b,c){s2.call(this,a,b,c);
this.B=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=Z2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},A3=function(a,b,c){s2.call(this,a,b,c);
this.J=b.image_url;this.B=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.G=!!b.is_paygated;this.K=!!b.user_has_entitlement;this.url=Z2({target:b.target||"new",value:b.url})},YBa=function(a){this.o=a;
this.A={}},ZBa=function(a){var b={};
b=(b["iv-event"]=1,b);g.VU(a.o,"iv",b,void 0)},E3=function(a,b,c,d){if(b){var e=B3(a,b);
a.A[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=C3(a,"cta_annotation_shown",e,c);D3(a,e,$Ba(b,d))}},F3=function(a,b,c,d,e,f){if(b){var k=B3(a,b);
k["iv-event"]=3;k["i-time"]=a.A[b]||"";d&&g.lc(k,d);b=C3(a,"cta_annotation_clicked",k,e);D3(a,k,b,c,f)}},G3=function(a,b){if(b){var c=B3(a,b);
c["iv-event"]=4;c["i-time"]=a.A[b]||"";var d=C3(a,"cta_annotation_closed",c);D3(a,c,d)}},$Ba=function(a,b){return b?(0,g.I)(a,g.Na(function(a,b){return g.fo(b,a)},b)):a},C3=function(a,b,c,d){d=d?g.gb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Y(a.o).experiments.o("enable_async_click_tracking")){a:{c=c["a-id"];a=a.o.getVideoData();if(a.gA){if((b=a.gA[b])&&g.mK(b)){a=g.rc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.ar){b=g.FF(a.ar,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},D3=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.C)(c||[],function(a){f++;
g.pG(a,m)});
e&&(f++,0!=e&&a.o.sendVideoStatsEngageEvent(e,m));g.VU(a.o,"iv",b,m)},B3=function(a,b){var c={};
if(b){var d=new g.On(b);(0,g.C)(d.Gb(),function(a){c[a]=escape(d.get(a,""))})}c["p-time"]=a.o.getCurrentTime().toFixed(2);
c.ps=g.Y(a.o).playerStyle;return c},H3=function(a,b,c,d,e){e=B3(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;D3(a,e,d)},I3=function(a,b,c,d){c&&(c=B3(a,c),c["iv-event"]=b,D3(a,c,d))},aCa=function(a,b,c,d,e,f,k){this.A=a;
this.B=b;this.D=c;this.videoData=d;this.logger=e;this.o=f;this.C=k},J3=function(a,b,c){this.o=a;
this.B=b;this.D=c;this.A=new g.lq(null)},cCa=function(a,b){var c=[];
(0,g.C)(b.choices,function(a){c.push({I:"li",N:b.G+"-"+a.index.toString(),P:[{I:"label",P:[{I:"input",N:"iv-card-poll-choice-input",T:{type:"checkbox",role:"radio",name:b.G+a.index.toString(),value:a.index.toString(),"data-poll-choice-index":a.index.toString()}},{I:"span",N:"iv-card-poll-choice-text",P:[{I:"span",N:"iv-card-poll-choice-percent"},K3(this,"span",void 0,a.desc)]}]},{I:"div",N:"iv-card-poll-result",P:[{I:"div",N:"iv-card-poll-result-bar"}]}]})},a);
var d={I:"ul",T:{role:"radiogroup"},P:c},e={};b.B&&(e["aria-label"]=g.wV("$POLL_TITLE - \u767b\u5f55\u5373\u53ef\u6295\u7968\u3002",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{I:"div",N:"iv-card-content",P:[K3(a,"h2",e,b.title),{I:"form",P:[{I:"fieldset",P:[d]}]}]}];b.B&&(f.push("iv-card-unavailable"),d.push({I:"div",da:["iv-card-sign-in"],P:[{I:"h2",ca:"\u60f3\u8981\u53c2\u4e0e\u6295\u7968\uff1f"},{I:"a",da:["iv-card-sign-in-button","iv-button"],T:{href:$2(b.B)},P:[{I:"span",da:["iv-button-content"],
ca:"\u767b\u5f55"}]}]}));f=new g.W({I:"div",da:f,P:d});d=f.element;bCa(b,d);cAa(a.o.A,d,g.Na(a.G,b),a);(0,g.C)(g.Xd("iv-card-poll-choice-input",d),function(a){this.o.A.X(a,"focus",g.Na(this.C,!0));this.o.A.X(a,"blur",g.Na(this.C,!1))},a);
b.B&&(d=g.Yd("iv-card-sign-in-button",d),a.B(d,b.B,b.id,b.Jd,b.C,b.A.click,5));return f},N3=function(a,b,c,d){var e=b.displayDomain?{I:"div",
N:"iv-card-image-text",ca:b.displayDomain}:"",f=dCa(a,b),k=["iv-card"];b.o&&k.push("iv-card-unavailable");e=[{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[L3(b.imageUrl,e),{I:"div",N:"iv-card-content",P:[K3(a,"h2",void 0,b.title),f]}]}];b.o&&e.push({I:"div",da:["iv-card-sign-in"],P:[K3(a,"h2",void 0,b.L||""),{I:"p",ca:b.K},{I:"a",da:["iv-card-sign-in-button","iv-button"],T:{href:$2(b.o)},P:[K3(a,"span","iv-button-content","\u767b\u5f55")]}]});k=new g.W({I:"div",da:k,P:e});M3(a,k,b,c,d);return k},
eCa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.K?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.G&&b.B?{I:"span",da:d,T:e,ca:b.B}:"";c={I:"div",da:["iv-card",c],P:[{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[L3(b.J,d?{I:"div",N:"iv-card-image-text",P:[d,b.priceText]}:""),{I:"div",N:"iv-card-content",P:[{I:"h2",N:"iv-card-primary-link",ca:b.title},O3(a,b)]}]}]};c=new g.W(c);M3(a,c,b);return c},P3=function(a,b){return b.customMessage?K3(a,"div",
"iv-card-message",b.customMessage):""},L3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{I:"div",N:"iv-card-image",T:{style:c},P:d}},O3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.C)(b.metaInfo,function(a){c.push(K3(this,"li","",a))},a);
return{I:"ul",N:"iv-card-meta-info",P:c}},K3=function(a,b,c,d){c?g.u(c)?c={"class":c}:g.Fa(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.mq(a.A,d);return{I:b,T:c,ca:d}},dCa=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.B&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.B+");");d.dir=g.mq(a.A,b.customMessage);var e=[{I:"span",ca:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({I:"span",N:"iv-card-link-icon"}));return{I:"div",da:c,T:d,P:e}},bCa=function(a,b){var c=0;
(0,g.C)(a.choices,function(a){c+=a.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Yd(a.G+"-"+e.index.toString(),b);e=e.count/c;null==a.o&&(e=0);g.T(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.o==d);f.getElementsByTagName("input")[0].checked=a.o==d;var k=Math.floor(100*e).toFixed(0),l=g.Yd("iv-card-poll-choice-percent",f);g.xe(l,g.wV("$PERCENT%",{PERCENT:k}));f=g.Yd("iv-card-poll-result-bar",f);g.Oh(f,"transform","scaleX("+e.toFixed(2)+")")}g.T(b,"iv-card-poll-voted",null!=a.o);g.T(b,"iv-card-poll-expanded",
null!=a.o&&1<a.choices.length)},fCa=function(a,b,c,d){d?(c&&a.o.videoData.Da||a.o.o.pauseVideo(),a.o.o.isFullscreen()&&a.o.o.toggleFullscreen(),F3(a.o.logger,b.C,d,void 0,b.A.click,5),(a=g.vI())&&g.iI(a,b.F)):b.url&&a.D(b.url,b.id,b.Jd,b.C,b.A.click||[],5)},M3=function(a,b,c,d,e){c.o&&gCa(a,g.Xd("iv-card-sign-in-button",b.element),c,c.o,e);
c.url&&gCa(a,g.Xd("iv-click-target",b.element),c,c.url,d)},gCa=function(a,b,c,d,e){(0,g.C)(b,function(a){if(e){var b=(0,g.z)(function(a){a.stopPropagation();
a.preventDefault();e();return!1},this);
this.o.A.X(a,"click",b)}else d&&this.B(a,d,c.id,c.Jd,c.C,c.A.click,5)},a)},hCa=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},Q3=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=iCa(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},iCa=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},jCa=function(a){a=$2(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!Q3(a))||(b=g.fh(g.eh(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.DF(a);if(!b||!b.v)return null;if(b=b.t)return hCa(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.BF(a[1]))&&a.t?hCa(a.t):-1},kCa=function(a){a=$2(a);
a=a.replace(/https?:\/\//g,"");return Q3(a)?(a=g.DF(a))&&a.v?a.v:null:null},lCa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},R3=function(a,b){return b?b:Q3(a)?"current":"new"},S3=function(a,b){g.J.call(this);
this.Fa=a;this.context=b;this.Ey=!1;this.ea=0},mCa=function(a){return(0,g.H)()-a.ea},nCa=function(a,b,c,d,e,f){var k=$2(b);
if(k){var l=R3(k,b.target),m=(0,g.z)(function(){b.o&&this.context.o.pauseVideo();var a=this.context.videoData.Jc||!1,d=g.DF(k||"");a&&d&&(d.v||d.list)?g.M0(this.context.o.app,d.v,c,d.list,!1,void 0,void 0):g.tV(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=mCa(a);F3(a.context.logger,d,m,n,e,f);Q3(k)||(a=g.vI(),d=c.itct,a&&d&&g.iI(a,g.eI(d)))}},V3=function(a,b,c){S3.call(this,b,c);
var d=this;this.A=a;this.Y=null;this.aa=this.ya=this.D=this.xa=!1;this.ba=null;this.V=new g.V(g.y,c.D.sd?4E3:3E3);g.K(this,this.V);this.ma=new g.V(g.y);g.K(this,this.ma);this.F=new J3(c,(0,g.z)(this.jl,this),(0,g.z)(this.hq,this));this.J=new g.W({I:"div",N:"iv-drawer",T:{id:"iv-drawer"},P:[{I:"div",N:"iv-drawer-header",T:{"aria-role":"heading"},P:[{I:"span",N:"iv-drawer-header-text"},{I:"button",da:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"\u9690\u85cf\u5361\u7247",tabindex:"0"}}]},
{I:"div",N:"iv-drawer-content"}]});g.K(this,this.J);this.G=this.J.element;this.ha=new g.JV(this.J,330);g.K(this,this.ha);this.za=g.Yd("iv-drawer-header-text",this.G);this.B=g.Yd("iv-drawer-content",this.G);this.C=[];this.sa=this.O=this.H=this.ga=this.o=null;this.L=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.ya&&T3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ya=d.D)&&U3(d)});
this.M=this.K=this.ia=null},tCa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&oCa[c]){c=new oCa[c](b.id,b.data,b.o);if(!a.xa){g.Ar(a.ra(),["html5-stop-propagation","iv-drawer-manager"]);g.cV(a.A,a.G,5);pCa(a);a.O=g.Yd("ytp-cards-button",a.A.getRootNode());var d=g.Yd("iv-drawer-close-button",a.G);a.sa=d;a.xa=!0}qCa(a,c.id);var e=rCa(a,c);if(e){d={jc:c,Mt:e.element,RC:!1};var f=sCa(a,d);g.lb(a.C,f,0,d);e.A(a.B,f);a.Po();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Na(a.EV,d)):(e=1E3*a.context.o.getCurrentTime(),5E3>e&&e>c.startMs&&a.bG(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Na(a.bG,d)),W3(a))}}},uCa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){T3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){U3(a)});
var c=b.data.headerText;g.xe(a.za,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.Y=b.data.eventId);a.ia=g.eI(b.data.trackingParams);a.M=g.eI(b.data.closeTrackingParams);a.K=g.eI(b.data.iconTrackingParams)},qCa=function(a,b){var c=vCa(a,b);
c&&(c==a.o&&(a.o=null),a.A.removeCueRange(c.jc.id),g.pe(c.Mt),g.cb(a.C,c),a.Po(),W3(a))},T3=function(a,b,c,d){if(!a.D){a.ha.show();
a.ga=new g.V(function(){g.S(a.context.o.getRootNode(),"ytp-iv-drawer-open")},0);
a.ga.start();a.ba=g.WG(a.B,"mousewheel",(0,g.z)(a.YN,a));a.D=!0;a.ea=(0,g.H)();H3(a.context.logger,a.Y,7,void 0,d&&d.jc?d.jc.C:void 0);var e=g.vI();e&&a.ia&&a.M&&q2(e,[a.ia,a.M]);var f={TRIGGER_TYPE:b};(0,g.C)(a.C,function(b){b.RC||(b.RC=!0,E3(a.context.logger,b.jc.C,b.jc.A.KM,f));e&&q2(e,[b.jc.F])});
i2(a.A);c&&(a.H=new g.V(function(){a.ka=a.O;a.sa.focus()},330),a.H.start())}},U3=function(a){a.D&&(a.ha.hide(),g.XG(a.ba),a.ba=null,g.Br(a.context.o.getRootNode(),"ytp-iv-drawer-open"),a.D=!1,i2(a.A),a.H&&a.H.stop(),a.H=new g.V(function(){a.ka&&(a.ka.focus(),a.ka=null)},330),a.H.start())},pCa=function(a){var b=g.Yd("iv-drawer-close-button",a.G);
a.context.A.X(b,"click",a.iK,a);a.context.A.X(a.B,"touchend",function(){a.V.start()});
a.context.A.X(a.B,"scroll",a.uK,a);a.context.C.subscribe("onHideControls",function(){a.aa=!0});
a.context.C.subscribe("onShowControls",function(){a.aa=!1});
a.context.C.subscribe("onVideoAreaChange",function(){a.aa=g.zr(a.A.getRootNode(),"ytp-autohide")});
a.L.push(g.nF("iv-button-shown",a.fN,a));a.L.push(g.nF("iv-button-hidden",a.eN,a));a.L.push(g.nF("iv-teaser-shown",a.iN,a));a.L.push(g.nF("iv-teaser-hidden",a.hN,a));a.L.push(g.nF("iv-teaser-clicked",a.gN,a))},rCa=function(a,b){switch(b.type){case "simple":return N3(a.F,b);
case "collaborator":var c=a.F,d={I:"div",da:["iv-card","iv-card-channel"],P:[{I:"a",da:["iv-click-target"],T:{href:$2(b.url),"data-ytid":b.channelId},P:[L3(b.profileImageUrl),{I:"div",N:"iv-card-content",P:[P3(c,b),{I:"h2",N:"iv-card-primary-link",ca:b.title},O3(c,b)]}]}]};d=new g.W(d);M3(c,d,b);return d;case "donation":return c=a.F,d=(0,g.z)(c.F,c,b),N3(c,b,d,d);case "episode":return eCa(a.F,b,"iv-card-episode");case "movie":return eCa(a.F,b,"iv-card-movie");case "playlist":return c=a.F,d={I:"div",
da:["iv-card","iv-card-playlist"],P:[{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[L3(b.B,{I:"div",N:"iv-card-image-overlay",P:[{I:"span",N:"iv-card-playlist-video-count",ca:b.playlistVideoCount.toString()}]}),{I:"div",N:"iv-card-content",P:[P3(c,b),K3(c,"h2","iv-card-primary-link",b.title),O3(c,b)]}]}]},d=new g.W(d),M3(c,d,b),d;case "poll":return cCa(a.F,b);case "productListing":c=a.F;var e=!g.Ya(b.offers);d=["iv-card"];var f="",k=dCa(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",
e=b.offers[0],k=[],e.price&&k.push({I:"div",N:"iv-card-offer-price",ca:e.price}),e.merchant&&k.push({I:"div",N:"iv-card-offer-merchant",ca:e.merchant}),k={I:"div",P:k});d={I:"div",da:d,T:{tabindex:"0"},P:[{I:"a",da:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+b.imageUrl+");",href:$2(b.url),"aria-hidden":"true",tabindex:"-1"}},{I:"div",N:"iv-card-content",P:[b.sponsored?{I:"div",N:"iv-card-sponsored",P:["\u8d5e\u52a9",{I:"div",N:"iv-ad-info-container",P:[{I:"div",N:"iv-ad-info",
ca:"{{adInfo}}"},{I:"div",N:"iv-ad-info-icon-container",P:[{I:"div",N:"iv-ad-info-icon"},{I:"div",N:"iv-ad-info-callout"}]}]}]}:"",{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[K3(c,"h2",f,b.title),k]}]}]};d=new g.W(d);f=g.je("span");g.xe(f,"\u60a8\u4e4b\u6240\u4ee5\u770b\u5230\u6b64\u4ea7\u54c1\u662f\u56e0\u4e3a\u6211\u4eec\u8ba4\u4e3a\u5b83\u4e0e\u8be5\u89c6\u9891\u76f8\u5173\u3002Google \u53ef\u80fd\u4f1a\u5411\u76f8\u5e94\u5546\u5bb6\u6536\u53d6\u5e7f\u544a\u8d39\u7528\u3002");d.Kb(f,"adInfo");
M3(c,d,b);return d;case "tip":return c=a.F,d=(0,g.z)(c.H,c,b),N3(c,b,d,d);case "video":return c=a.F,d=b.isLiveNow?{I:"span",da:["yt-badge","yt-badge-live"],ca:"\u6b63\u5728\u76f4\u64ad"}:"",d={I:"div",da:["iv-card","iv-card-video"],P:[{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[L3(b.B,b.videoDuration?{I:"span",N:"iv-card-video-duration",ca:b.videoDuration}:""),{I:"div",N:"iv-card-content",P:[P3(c,b),K3(c,"h2","iv-card-primary-link",b.title),O3(c,b),d]}]}]},d=new g.W(d),M3(c,d,b),d}return null},
sCa=function(a,b){if(0==a.C.length)return 0;
var c=g.Ua(a.C,function(a){return b.jc.startMs>a.jc.startMs||b.jc.startMs==a.jc.startMs&&b.jc.timestamp>=a.jc.timestamp?!0:!1});
return-1==c?0:c+1},wCa=function(a){return a.o?"productListing"==a.o.jc.type:(0,g.vj)(a.C,function(a){return"productListing"==a.jc.type})},W3=function(a){g.T(a.A.getRootNode(),"ytp-cards-shopping-active",wCa(a))},xCa=function(a,b){if(a.J.C){var c=new n2([0,
a.B.scrollTop],[0,b.Mt.offsetTop],600,pAa);a.context.B.X(c,"animate",function(b){a.B.scrollTop=b.y});
a.context.B.X(c,"finish",function(b){a.B.scrollTop=b.y});
c.play()}else g.kQ(a.J,!0),a.B.scrollTop=b.Mt.offsetTop,g.kQ(a.J,!1)},X3=function(a){return a.o&&a.o.jc?a.o.jc:a.C[0]&&a.C[0].jc?a.C[0].jc:null},vCa=function(a,b){return g.Ta(a.C,function(a){return a.jc.id==b})},Y3=function(a,b,c){S3.call(this,a,b);
this.annotation=c;this.isActive=!1},yCa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},Z3=function(a,b,c){Y3.call(this,a,b,c);
this.A=null;this.G=!1;this.C=null;this.B=!1;this.H=0;this.o=this.F=this.D=null},$3=function(a,b,c){Y3.call(this,a,b,c);
this.J=this.D=this.K=!1;this.G=5E3;this.B=null;this.H=g.he("DIV","iv-promo-contents");this.A=this.C=this.o=null;this.F=new g.V(function(){this.o.setAttribute("aria-hidden",!0);g.L(this.C,!1);g.L(this.A,!0)},700,this);
g.K(this,this.F)},zCa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.ra().setAttribute("aria-hidden",!0);a.ra().setAttribute("aria-label","\u5ba3\u4f20");a.ra().tabIndex=0;var e=a.annotation.Xa(),f=b.image_url;if(f){var k=g.he("DIV",["iv-promo-img","iv-click-target"]);f=g.he("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.he("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.he("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.jl(k,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}e?(f=g.he("A","iv-promo-txt"),g.Dd(f,$2(e)),a.o=f):a.o=g.he("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.he("P",null,g.he("STRONG",null,b.text_line_1));var m=g.he("P",null,g.he("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
a.context.D.experiments.o("web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.he("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.he("BUTTON",["iv-button","iv-promo-button"],g.he("SPAN","iv-button-content",f));var p=g.he("DIV","iv-promo-button-container");p.appendChild(f);e&&a.jl(a.ra(),e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}g.S(a.o,"iv-click-target");e&&a.jl(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c);break;case "playlist":case "video":l=
g.he("P",null,g.he("SPAN",null,b.text_line_1)),m=g.he("P",null,g.he("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.he("SPAN",["yt-badge","iv-promo-badge-live"],"\u6b63\u5728\u76f4\u64ad")),g.S(a.o,"iv-click-target"),e&&a.jl(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);p&&a.H.appendChild(p);c=g.he("DIV","iv-promo-actions");a.A=g.he("BUTTON",["iv-promo-expand","ytp-button"]);a.A.title="\u5c55\u5f00";
a.context.A.X(a.A,"click",g.Na(a.Ku,5E3),a);c.appendChild(a.A);g.L(a.A,!1);a.context.A.X(a.ra(),"mouseover",a.tL,a);a.context.A.X(a.ra(),"mouseout",a.sL,a);a.context.A.X(a.ra(),"touchend",g.Na(a.Ku,5E3),a);a.C=g.he("BUTTON",["iv-promo-close","ytp-button"]);a.C.title="\u5173\u95ed";a.context.A.X(a.C,"click","cta"==a.annotation.style&&b.text_line_3?a.iL:a.xO,a);c.appendChild(a.C);g.Ar(a.ra(),d);k&&(a.ra().appendChild(k),n&&k.appendChild(n));a.ra().appendChild(a.H);a.ra().appendChild(c)},ACa=function(a){a.D||
a.J||a.B||(g.S(a.ra(),"iv-promo-collapsed"),a.D=!0,a.F.start())},BCa=function(a){a.F.stop();
a.D&&(g.Cr(a.ra(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.D=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.L(a.A,!1),g.L(a.C,!0))},CCa=function(a,b){a.B||(a.B=g.Ug(function(){a4(this);
ACa(this)},b,a))},a4=function(a){a.B&&(g.Vg(a.B),a.B=null)},b4=function(a){g.lV.call(this,a);
this.K=!1;this.J=0;this.A={};this.L={};this.kb=new YBa(a);this.G=new g.jH(this);g.K(this,this.G);this.F=this.C=null;this.G.R(this.player,"onVideoAreaChange",(0,g.z)(this.U,this,"onVideoAreaChange"));this.G.R(this.player,"onHideControls",(0,g.z)(this.U,this,"onHideControls"));this.G.R(this.player,"onShowControls",(0,g.z)(this.U,this,"onShowControls"));this.G.R(this.player,"resize",(0,g.z)(this.U,this,"resize"));this.G.R(this.player,"presentingplayerstatechange",(0,g.z)(this.U,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.ER,this);this.subscribe("onShowControls",this.LT,this);this.subscribe("presentingplayerstatechange",this.RS,this);this.subscribe("resize",this.Tw,this);this.subscribe("G",this.EN,this);this.subscribe("F",this.Uh,this);this.subscribe("D",this.nQ,this);this.subscribe("E",this.TQ,this);g.Y(this.player).J.subscribe("vast_info_card_add",this.hF,this);this.O=new g.jH(this);g.K(this,this.O);this.O.R(this.player,g.nR("annotations_module"),this.CN);this.O.R(this.player,
"crx_annotations_module",this.DN);this.V=g.he("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Y=g.he("DIV","video-custom-annotations");this.D=new g.W({I:"div",da:["ytp-player-content","ytp-iv-player-content"]});g.K(this,this.D);g.cV(this.player,this.D.element,4);this.D.hide();this.B=new g.W({I:"div",da:["ytp-iv-video-content"]});g.K(this,this.B);g.le(this.B.element,g.he("DIV","video-annotations",this.V,this.Y));this.H=this.o=null;this.M=[];DCa(this)&&this.load();var b=g.je("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ef(this,function(){g.pe(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},ECa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},DCa=function(a){var b=g.Y(a.player);
a=a.player.getVideoData();return 1==(b.ih||a.ih)&&!a.Al||null!==b.J.get(a.videoId)},FCa=function(a,b,c){a.K=!0;
a.F=g.UF(b,c)},GCa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(GCa(a,e))}return c},HCa=function(a,b,c){return!(a.loaded&&a.J==b&&a.player.getVideoData().videoId==
c)},JCa=function(a,b){var c=ICa(a,b);
if(!c&&"marker"!=b.type)return null;uBa(b,function(a){a=(0,g.z)(this.nU,this,b.id,a);this.subscribe("ivTrigger:"+b.id,a)},a);
var d=new x3(a.ha,b,c);g.K(d,c);return d},KCa=function(a,b){var c=g.he("DIV",["annotation",
"annotation-type-custom"]);g.L(c,!1);var d=null;switch(b.type){case "branding":if(g.Y(a.player).fd)break;a.D.element.appendChild(c);d=new Z3(c,c4(a),b);break;case "promotion":g.cV(a.player,c,4),d=new $3(c,c4(a),b)}d&&d.Fr();return d},NCa=function(a){var b=a.player.getVideoData();
if(b.re){var c=g.Y(a.player),d=c.J.get(b.videoId);if(d){var e={format:"XML",bd:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.bd.gaming="1");e.Hd=(0,g.z)(function(a,b,c){HCa(this,a,b)||(a=g.PF(c)&&c.responseXML?c.responseXML:null)&&d4(this,a)},a,a.J,b.videoId);
g.PH()&&(e.Hd=LCa(a,e.Hd));e.Rb={ic_only:"1"};MCa(e,d);a.K=!0;g.UF(b.re,e)}}},MCa=function(a,b){a.method="POST";
a.Rb=a.Rb||{};b.Lt&&(a.Rb.ic_coll=b.Lt);b.pi&&(a.Rb.ic_xml=b.pi);b.rl&&(a.Rb.ic_track=b.rl)},OCa=function(a){var b=new g.W({I:"div"});
g.L(b.element,!1);var c=new V3(a.player,b.element,c4(a));g.K(c,b);b.A(a.D.element);c.Fr();return c},c4=function(a){if(!a.H){var b=new g.gH(a);
g.K(a,b);var c=new g.Xn(a);g.K(a,c);a.H=new aCa(b,c,g.Y(a.player),a.player.getVideoData(),a.kb,a.player,a.ha)}return a.H},d4=function(a,b){var c=!1;
PCa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=GCa(a,d[e]),k=null;try{k=rBa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=KCa(a,k))g.K(a,f),a.L[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.o||(a.o=OCa(a),g.K(a,a.o)),"card"==k.type?tCa(a.o,k):uCa(a.o,k),c=!0;else if(f=JCa(a,k))g.K(a,f),a.A[k.id]=f}}c&&(i2(a.player),a.Tw());g.Mb(a.A,function(a){if(a.view){var b=a.annotation;(a=a.view)&&b.segment&&b.segment.A&&
(b=this.A[b.segment.A])&&(a.O=b.annotation)}},a)},PCa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.vI();
if(b){var c=g.uI();c&&g.gI(b,c,[g.eI(a)])}}},RCa=function(a,b,c,d){d?QCa(a,b,c):e4(a,b,c)},e4=function(a,b,c){if(b=a.A[b])y3(b),c&&c.A?(a=(0,g.z)(a.fC,a,b),b.o=new g.V(a,2E3),b.o.start()):a.fC(b)},QCa=function(a,b,c){if(b=a.A[b])y3(b),c&&c.B?(a=(0,g.z)(a.nG,a,b),b.o=new g.V(a,2E3),b.o.start()):a.nG(b)},SCa=function(a,b){var c=a.player.getVideoData();
if(!c.Jo)return!1;var d=$2(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!Q3(d))return!1;d=g.DF(d);return d.list||d.p?!1:(d=kCa(b))?c.videoId==d?!0:"new"!=b.target&&g.Y(a.player).o?!0:!1:!1},ICa=function(a,b){if(TCa(b)){var c=b.D||f3(b,function(a){return"click"==a||"rollOut"==a||"rollOut"==a});
return new s3(b,(0,g.z)(a.V.appendChild,a.V),a.player,a.ha,c)}return null},TCa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in e3)if(a.style==e3[b])return!0;return!1},f4=function(a,b,c,d){a.U(yBa(b,d),c,d)},LCa=function(a,b){return(0,g.z)(function(){if(!this.la()){var a=Array.prototype.slice.call(arguments,0);
a.unshift(b);b=g.Na.apply(window,a);this.M.push(g.NH(b))}},a)};
g.KU.prototype.dl=g.ca(13,function(a,b){var c=g.LU(this).B;c&&c.dl(a,b)});
var eAa=/[^\d]+$/,fAa={cm:1,"in":1,mm:1,pc:1,pt:1},gAa={em:1,ex:1};j2.prototype.clone=function(){return new j2(this.start,this.end)};
j2.prototype.getLength=function(){return this.end-this.start};
var k2={},l2=null;g.B(mAa,g.Hf);g.B(n2,g.Nu);g.h=n2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.sb())return!1;m2(this);this.startTime=a=(0,g.H)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Lq();this.Ke("play");-1==this.o&&this.Ke("resume");this.o=1;var b=g.Ma(this);b in k2||(k2[b]=this);kAa();lAa(this,a);return!0};
g.h.stop=function(a){m2(this);this.o=0;a&&(this.progress=1);nAa(this,this.progress);this.Ke("stop");this.Gn()};
g.h.pause=function(){this.sb()&&(m2(this),this.o=-1,this.Ke("pause"))};
g.h.W=function(){0==this.o||this.stop(!1);this.Ke("destroy");n2.fa.W.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Kw=function(){this.Ke("animate")};
g.h.Ke=function(a){this.dispatchEvent(new mAa(a,this))};
g.B(o2,n2);o2.prototype.C=g.y;o2.prototype.Kw=function(){this.C();o2.fa.Kw.call(this)};
o2.prototype.Gn=function(){this.C();o2.fa.Gn.call(this)};
o2.prototype.Lq=function(){this.C();o2.fa.Lq.call(this)};
g.B(p2,o2);p2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.B(t2,g.ig);g.h=t2.prototype;g.h.Fu=null;g.h.Km=null;g.h.ra=function(){return this.Km};
g.h.addEventListener=function(a,b,c,d){g.Uf(this.Km,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.cg(this.Km,a,b,c,d)};
g.h.W=function(){t2.fa.W.call(this);var a=this.Km;if(a)if(g.Nf(a))a.Le&&g.Rf(a.Le);else if(a=g.Xf(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.dg(d[e])&&++b}};g.B(x2,t2);x2.prototype.fill=null;g.B(tAa,t2);y2.prototype.Mf=null;y2.prototype.fe=null;y2.prototype.Wn=!0;var uAa=[2,2,6,6,0];g.h=y2.prototype;g.h.clear=function(){this.ub.length=0;this.Pa.length=0;this.Ie.length=0;delete this.Mf;delete this.fe;delete this.Wn;return this};
g.h.moveTo=function(a,b){0==g.Ra(this.ub)?this.Ie.length-=2:(this.ub.push(0),this.Pa.push(1));this.Ie.push(a,b);this.fe=this.Mf=[a,b];return this};
g.h.Ic=function(a){var b=g.Ra(this.ub);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.ub.push(1),this.Pa.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Ie.push(c,d)}this.Pa[this.Pa.length-1]+=b/2;this.fe=[c,d]};
g.h.close=function(){var a=g.Ra(this.ub);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.ub.push(4),this.Pa.push(1),this.fe=this.Mf);return this};
g.h.clone=function(){var a=new this.constructor;a.ub=this.ub.concat();a.Pa=this.Pa.concat();a.Ie=this.Ie.concat();a.Mf=this.Mf&&this.Mf.concat();a.fe=this.fe&&this.fe.concat();a.Wn=this.Wn;return a};
g.h.transform=function(a){if(!this.Wn)throw Error("Non-simple path");a.transform(this.Ie,0,this.Ie,0,this.Ie.length/2);this.Mf&&a.transform(this.Mf,0,this.Mf,0,1);this.fe&&this.Mf!=this.fe&&a.transform(this.fe,0,this.fe,0,1);return this};
g.h.isEmpty=function(){return 0==this.ub.length};g.B(wAa,x2);A2.prototype.ab=function(){return this.A};g.B(B2,g.kw);B2.prototype.C=null;B2.prototype.Zj=function(){return this.Ye?g.gi(this.ra()):g.Ba(this.width)&&g.Ba(this.height)?new g.Pd(this.width,this.height):null};
B2.prototype.resume=function(){};g.B(xAa,t2);g.B(v2,sAa);g.B(u2,sAa);g.B(C2,tAa);C2.prototype.clear=function(){g.ne(this.ra())};
C2.prototype.setSize=function(a,b){F2(this.ra(),{width:a,height:b})};
g.B(yAa,wAa);g.B(D2,xAa);D2.prototype.setSize=function(a,b){F2(this.ra(),{width:a,height:b})};var H2;g.B(E2,B2);var AAa=0;g.h=E2.prototype;g.h.Gp=function(){var a=w2(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=w2(this,"g");this.H=w2(this,"defs");this.C=new C2(b,this);a.appendChild(this.H);a.appendChild(b);this.o=a;this.B&&(this.ra().setAttribute("preserveAspectRatio","none"),this.V?this.Tr():this.ra().setAttribute("viewBox","0 0 "+(this.B?this.B+" "+this.M:"")))};
g.h.Tr=function(){if(this.Ye){var a=this.Zj();if(0==a.width)this.ra().style.visibility="hidden";else{this.ra().style.visibility="";var b=a.width/this.B;a=a.height/this.M;this.C.ra().setAttribute("transform","scale("+b+" "+a+") translate(0 0)")}}};
g.h.setSize=function(a,b){g.fi(this.ra(),a,b)};
g.h.Zj=function(){if(!g.Qh)return this.Ye?g.gi(this.ra()):E2.fa.Zj.call(this);var a=this.width,b=this.height,c=g.u(a)&&-1!=a.indexOf("%"),d=g.u(b)&&-1!=b.indexOf("%");if(!this.Ye&&(c||d))return null;if(c){var e=this.ra().parentNode;var f=g.gi(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ra().parentNode,f=f||g.gi(e),b=parseFloat(b)*f.height/100);return new g.Pd(a,b)};
g.h.clear=function(){this.C.clear();g.ne(this.H);this.A={}};
g.h.drawImage=function(a,b,c,d,e,f){a=w2(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new D2(a,this);(f||this.C).ra().appendChild(e.ra());return e};
g.h.Rj=function(){var a=this.Zj();E2.fa.Rj.call(this);a||this.dispatchEvent("resize");if(this.V){a=this.width;var b=this.height;"string"==typeof a&&-1!=a.indexOf("%")&&"string"==typeof b&&-1!=b.indexOf("%")&&this.K.X(BAa(),"tick",this.Tr);this.Tr()}};
g.h.lm=function(){E2.fa.lm.call(this);this.V&&this.K.Ka(BAa(),"tick",this.Tr)};
g.h.W=function(){delete this.A;delete this.H;delete this.C;this.K.dispose();delete this.K;E2.fa.W.call(this)};g.r(J2,g.lV);g.h=J2.prototype;
g.h.load=function(){g.lV.prototype.load.call(this);if(!K2(g.Y(this.player).playerStyle)){var a=g.Fna(this.player.getVideoData());if(a)a=I2(a,CAa(this)),L2(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",Hd:(0,g.z)(this.rR,this,a),bd:{v:a},withCredentials:!0};"gaming"==g.Y(this.player).playerStyle&&(a.bd.gaming="1");this.M&&(a.bd.ptype="embedded");var c=this.player.getVideoData().iB;c&&(a.Rb={ad_tracking:c});if(b=g.Ena(b))if(b=g.hd(b),b=g.ed(b))this.B=
g.UF(b,a)}}};
g.h.unload=function(){L2(this,null);this.B&&(this.B.abort(),this.B=null);g.lV.prototype.unload.call(this)};
g.h.Gc=function(a,b){if(!K2(g.Y(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=I2(b,"new");L2(this,c);return!0}return null};
g.h.getOptions=function(){return K2(g.Y(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.rR=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=I2(c,CAa(this)))}L2(this,c)};
g.h.kD=function(){if(this.A&&this.A.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<UCa.length;f++){var k=Math.abs(b.width-UCa[f]);if(-1==e||d>=k)e=f,d=k}d=VCa[e];this.C&&g.Oh(this.C.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.A.elements.length;++b)if(f=this.A.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.fi(e.element,Math.round(k.width*a.width),f);g.Vh(e.element,m,n);g.Cr(e.element,WCa);m=k.left+k.width/2;k=k.top+l/2;g.S(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Cr(e.element,VCa);g.S(e.element,d);(e=g.Wd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Oh(e,"height",f+"px")}}}}};
g.h.GN=function(a){if(this.A)if("ytp-ce-in-endscreen"==a.getId())this.K=!1,this.A.skip&&1==this.player.getPlayerState()?(g.SU(this.player,!0),this.player.seekTo(Infinity),this.K=!0):(O2(this,this.A.impressionUrls),(a=g.vI())&&this.A.visualElement&&g.hI(a,this.A.visualElement));else if(!this.K){a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.S(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.S(b,"ytp-ce-shown");O2(this,c.impressionUrls);
(b=g.vI())&&g.hI(b,c.visualElement);g.Y(this.player).Nb&&this.player.Ba("endscreenelementshown",a)}};
g.h.HN=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.K){a=a.getId().substring(15);var b=this.o[a];g.Br(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Br(b,"ytp-ce-shown");g.Y(this.player).Nb&&this.player.Ba("endscreenelementhidden",a)}};
g.h.HU=function(a){var b=this;a.target===window&&(new g.V(function(){for(var a in b.o)g.Cr(b.o[a].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.DE=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.zr(c,"ytp-ce-element");){g.zr(c,"subscribe-label")&&P2(this,a);if(g.zr(c,"ytp-ce-channel-subscribe"))return;c=g.ue(c)}if(!c||g.zr(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Sw(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Nr?(P2(this,a),this.TF(),this.player.pauseVideo(),c=g.hd(a.targetUrl),c=g.ed(c),g.tV(c,void 0,a.Jd)):(c=this.player.getVideoData().Jc,
c=(0,g.z)(this.NV,this,c,a.targetUrl,a.Jd),c=(0,g.z)(this.TF,this,c),P2(this,a,c))}}};
g.h.NV=function(a,b,c){var d=g.DF(b);a&&d&&(d.v||d.list)?g.M0(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.sV(b,c)};
g.h.dw=function(a,b){g.zr(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.S(a.element,"ytp-ce-element-hover"):g.Y(this.player).A?(new g.V(function(){g.S(a.element,"ytp-ce-element-hover")},200)).start():g.S(a.element,"ytp-ce-element-hover"),O2(this,b.XL),N2(this,b.id,!0))};
g.h.Sw=function(a,b){g.Br(a.element,"ytp-ce-element-hover");g.Br(a.element,"ytp-ce-force-expand");N2(this,b.id,!1)};
g.h.TF=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var UCa=[346,426,470,506,570,640,853,1280,1920],VCa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),WCa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var OAa={eZ:"current",l1:"new"};var QAa={CLOSE:"close",q1:"openUrl",tJ:"subscribe"},RAa={Ks:"click",CLOSE:"close",x_:"hidden",p2:"rollOut",mJ:"rollOver",oJ:"shown"};var UAa={o4:"xx",p4:"xy",v4:"yx",w4:"yy"};g.r($Aa,b3);var fBa={UH:"anchored",b2:"rect",E2:"shapeless"};var kBa={CLOSED:"closed",B1:"playerControlShow",mJ:"rollOver",oJ:"shown"};d3.prototype.Xa=function(){var a=tBa(this,function(a){return"openUrl"==a.type&&null!=a.url});
return a?a.url:null};
d3.prototype.showLinkIcon=function(){return f3(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var e3={UH:"anchored",XH:"branding",CHANNEL:"channel",dZ:"cta",A_:"highlightText",c0:"label",PLAYLIST:"playlist",N1:"popup",S2:"speech",tJ:"subscribe",s3:"title",VIDEO:"video",h4:"website"},pBa={XH:"branding",AY:"card",IZ:"drawer",z_:"highlight",y0:"marker",T1:"promotion",TEXT:"text",l4:"widget"},qBa={Y3:"video_relative",C1:"player_relative"};zBa.prototype.B=function(a,b,c,d){this.o[a]=b?!c:c;a=g.Rb(this.o,function(a){return a});
this.C!=a&&(this.C=a,this.A.U(this.D,a,d))};i3.prototype.ra=function(){return this.D};
i3.prototype.C=function(){};var m3={bevel:1,dropshadow:2};g.r(o3,i3);
o3.prototype.C=function(a,b){var c=h3(a);if(c){var d=c3(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=wBa(a))&&c.o?c.o:null)&&c.length?c[0]:null){var f=g.Eh(WAa(b,XAa(e,new g.Bh(e.H,e.J,e.zl,e.C),b.o))),k=d.clone();c=new g.Bh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.A;k=n3(k,c.effects);l=j3(this,k.width,k.height);m=HBa(c,k.width,k.height,
this.o);d=new g.Bh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.Nd(f.x-k.left,f.y-k.top);this.B=17*a3(b.o,e.A,e.o?e.o:"xy");e=c.cornerRadius;f=a.A;var p=this.o&&g3(a),t=p?f.borderWidth+1:f.borderWidth;p=(f=t?new A2(t,p?f.A:f.borderColor):null)?f.ab()/2:0;t=JBa(d,n);var v=this.F(d,e,n,t),A=n.x;n=n.y;var E=d.width,G=d.height,M=d.left;d=d.top;var U=new y2;U.moveTo(M+e+p,d+p);"t"==t&&(U.Ic(v.start,d+p),U.Ic(A,n),U.Ic(v.end,d+p));U.Ic(M+E-e-p,d+p);z2(U,e,e,-90);"r"==t&&(U.Ic(M+E-p,v.start),
U.Ic(A,n),U.Ic(M+E-p,v.end));U.Ic(M+E-p,d+G-e-p);z2(U,e,e,0);"b"==t&&(U.Ic(v.end,d+G-p),U.Ic(A,n),U.Ic(v.start,d+G-p));U.Ic(M+e+p,d+G-p);z2(U,e,e,90);"l"==t&&(U.Ic(M+p,v.end),U.Ic(A,n),U.Ic(M+p,v.start));U.Ic(M+p,d+e+p);z2(U,e,e,180);U.close();G2(l,U,f,m);if(m=this.ra())g.S(m,"annotation-shape"),g.S(m,"annotation-speech-shape"),g.Vh(m,k.left,k.top),g.fi(m,k.width,k.height),IBa(l,m,c.effects)}}}};
o3.prototype.F=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=g.Hd(c-a/2,d+b,d+e-a-b);return new j2(c,c+a)}
return"t"==d||"b"==d?e(this.B,c.x,a.left,a.width):"l"==d||"r"==d?e(this.B,c.y,a.top,a.height):new j2(0,0)};g.r(p3,i3);p3.prototype.C=function(a,b){var c=h3(a);if(c){var d=c3(c,b);if(!(0>=d.width||0>=d.height)){var e=a.A;c=n3(d,e.effects);var f=j3(this,c.width,c.height),k=new g.Bh(0,0,d.width,d.height),l=e.cornerRadius;d=new A2(!e.C&&this.o?1:e.C,e.bgColor);var m=new u2("#000",0),n=d?d.ab()/2+1:0;k=GBa(k,l,n);G2(f,k,d,m);f=this.ra();g.S(f,"annotation-shape");e=e.o;g.ii(f,this.o?Math.max(e,.9):e);g.Vh(f,c.left,c.top);g.fi(f,c.width,c.height)}}};g.r(q3,i3);
q3.prototype.C=function(a,b){var c=h3(a);if(c){var d=c3(c,b);if(!(0>=d.width||0>=d.height)){c=a.A;var e=n3(d,c.effects),f=j3(this,e.width,e.height),k=new g.Bh(0,0,d.width,d.height);d=HBa(c,d.width,d.height,this.o);var l=c.cornerRadius;var m=a.A;var n=this.o&&g3(a),p=n?m.borderWidth+1:m.borderWidth;n=(m=p?new A2(p,n?m.A:m.borderColor):null)?m.ab()/2+1:0;k=GBa(k,l,n);G2(f,k,m,d);if(k=this.ra())g.S(k,"annotation-shape"),g.S(k,"annotation-popup-shape"),g.Vh(k,e.left,e.top),g.fi(k,e.width,e.height),IBa(f,
k,c.effects)}}};g.r(r3,o3);r3.prototype.F=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=c<=d+e/2?Math.max(d+e/4-a/2,d+b):Math.min(d+3*e/4-a/2,d+e-a-b);return new j2(c,c+a)}
return"t"==d||"b"==d?e(this.B,c.x,a.left,a.width):"l"==d||"r"==d?e(this.B,c.y,a.top,a.height):new j2(0,0)};g.r(s3,g.J);g.h=s3.prototype;g.h.tD=function(){this.J||(this.B&&g.L(this.B,!0),this.D&&g.L(this.D,!0),this.C&&(this.C.o=!0,g.ii(this.A,w3(this)?1:0),this.C.C(this.o,u3(this))),this.H.isActive()&&this.H.stop(),this.J=!0,this.K=this.Z.Mh(g.PU(this.F),"mouseleave",function(a){this.Jq.stop();this.Uh(a)}))};
g.h.Uh=function(){this.J&&(this.V?this.H.start():this.gC(),this.C&&(this.C.o=!1,g.ii(this.A,w3(this)?1:0),this.C.C(this.o,u3(this))),this.J=!1,this.K&&(this.Z.Ka(this.K),this.K=null))};
g.h.gC=function(){this.B&&g.L(this.B,!1);this.D&&g.L(this.D,!1)};
g.h.wO=function(a){this.ba=a;this.Jq.Im()};
g.h.rL=function(){var a=this.ba,b=new g.Nd(a.clientX,a.clientY),c=g.Zh(this.F.getRootNode()),d=NBa(c,this.M);c=(this.D&&g.ji(this.D)||this.B&&g.ji(this.B))&&NBa(c,this.V);d&&d.contains(b)||c&&c.contains(b)?this.tD(a):this.Uh(a)};
g.h.show=function(){var a=this.o.A;a=(a&&0==a.o||"title"==this.o.style||"highlightText"==this.o.style?!1:!0)&&!this.C;var b=!this.A;if(a){var c=u3(this),d=null;"highlight"==this.o.type||"label"==this.o.style?d=new p3:"popup"==this.o.style?d=new q3:"anchored"==this.o.style?d=new o3:"speech"==this.o.style&&(d=new r3);d&&(d.C(this.o,c),this.C=d,c=d.ra())&&(g.L(c,!1),g.S(c,"annotation-type-"+this.o.type.toLowerCase()),this.Y(c))}if(b){c=["annotation"];"highlightText"!=this.o.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.o.type.toLowerCase());this.A=g.he("DIV",c);g.L(this.A,!1);this.o.B&&(this.G=g.he("DIV","inner-text"),"label"==this.o.style&&(g.S(this.G,"player-label-text"),this.G.style.backgroundColor=this.o.A.bgColor),g.xe(this.G,this.o.B),this.A.appendChild(this.G));g.dF(this.A,"annotation_id",this.o.id);this.Y(this.A);KBa(this,this.A);if(g3(this.o)&&this.o.showLinkIcon()){if(d=this.o.Xa())c=this.A,d=new g.Hn($2(d)),c.title=d.A+d.C;this.D=g.he("SPAN","annotation-link-icon");g.L(this.D,
!1);this.A.appendChild(this.D)}LBa(this);g3(this.o)||(this.A.style.cursor="default")}if(a||b){a:{a=this.o.segment.o;if(a.length&&(a=hBa(a[0]))){a=a.D;break a}a=0}this.A&&(this.A.style.zIndex=a);this.C&&this.C.ra()&&(this.C.ra().style.zIndex=a)}g.L(this.A,!0);g.ii(this.A,w3(this)?1:0);v3(this);this.C&&this.C.ra()&&g.L(this.C.ra(),!0)};
g.h.hide=function(){this.A&&g.L(this.A,!1);this.C&&this.C.ra()&&g.L(this.C.ra(),!1);this.L&&(this.Z.Ka(this.L),this.L=null)};g.r(x3,g.J);g.h=x3.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(PBa(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.A.subscribe("resize",this.sD,this),this.A.subscribe("onVideoAreaChange",this.iF,this))};
g.h.destroy=function(){if(this.view){PBa(this);var a=this.view;g.hH(a.Z);a.Jq.dispose();a.H.dispose();a.A&&g.pe(a.A);a.C&&a.C.ra()&&g.pe(a.C.ra())}y3(this)};
g.h.iF=function(){v3(this.view)};
g.h.sD=function(){v3(this.view)};g.r(QBa,s2);g.r(z3,s2);g.r(RBa,z3);g.r(SBa,s2);g.r(TBa,s2);g.r(VBa,z3);g.r(WBa,z3);g.r(XBa,s2);g.r(A3,s2);J3.prototype.C=function(a,b){var c=g.De(b.target,"label");c&&g.T(c,"iv-card-poll-choice-focused",a)};
J3.prototype.G=function(a,b){var c=g.Ee(b.target,"iv-card-poll");if(c)if(a.B)g.Yd("iv-card-sign-in-button",c).click();else{var d=parseInt(iAa(b.target),10);if(null==a.o)a.choices[d].count++,a.o=d;else if(a.o!=d){var e=a.choices[a.o];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.o=d}else e=a.choices[a.o],e.count=Math.max(e.count-1,0),a.o=null;bCa(a,c);g.YF(this.o.videoData.re,{bd:{action_poll_vote:1},Rb:{poll_id:a.id,index:d,session_token:a.J}});F3(this.o.logger,a.C,void 0,{"link-id":d},a.A.click,
5);(c=g.vI())&&g.iI(c,a.F)}};
J3.prototype.F=function(a){var b=g.x("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.J,a.G)});
fCa(this,a,!0,c)};
J3.prototype.H=function(a){var b=g.x("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Na(b,a.M,a.J,a.G));fCa(this,a,!1,b)};g.r(S3,g.J);g.h=S3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.lR(a,b,{id:c});g.K(this,a);a.namespace="annotations_module";d&&dAa(a).subscribe("onEnter",d,this);e&&dAa(a).subscribe("onExit",e,this);g.YU(this.context.o,[a])};
g.h.Fr=function(){this.context.C.subscribe("resize",this.Po,this)};
g.h.ra=function(){return this.Fa};
g.h.jl=function(a,b,c,d,e,f,k){this.context.A.X(a,"click",g.Na(this.hq,b,c,d,e,f||[],k||0),this);this.context.A.X(a,"touchstart",g.Na(function(){this.Ey=!1}),this);
this.context.A.X(a,"touchmove",g.Na(function(){this.Ey=!0}),this)};
g.h.hq=function(a,b,c,d,e,f,k){if(this.Ey)return!1;k&&(k.stopPropagation(),k.preventDefault());nCa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.ea=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.pe(this.ra())};
g.h.Po=function(){};g.r(V3,S3);g.h=V3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.C.length)(a=this.A.getRootNode())?(a=g.gi(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Po=function(){var a=this.isAvailable();g.L(this.ra(),a);g.T(this.context.o.getRootNode(),"ytp-iv-drawer-enabled",a);i2(this.A)};
g.h.destroy=function(){this.A.dl(!1);this.A.getRootNode().removeChild(this.G);g.oF(this.L);g.XG(this.ba);this.ga&&this.ga.dispose();this.H&&this.H.dispose();S3.prototype.destroy.call(this)};
g.h.YN=function(a){this.V.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.bG=function(a){if(!g.zr(this.A.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.vI(),c=this.o?this.o.jc.D:this.K;b&&c&&r2(b,[c]);this.o=a;W3(this)}g.ji(this.ra())&&(2==this.context.o.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.o.getAdState():void 0):(b=isNaN(void 0)?this.context.o.getPlayerState():void 0,b=1==b||0==b&&0===this.context.o.getCurrentTime()),b&&a.jc.teaserDurationMs&&this.A.dl(!0,{teaserText:a.jc.teaserText,durationMs:a.jc.teaserDurationMs}));this.ma.isActive()||
((!this.D||!this.V.isActive()&&this.aa)&&xCa(this,a),this.ma.start(910+a.jc.teaserDurationMs))}};
g.h.EV=function(a){this.D||(this.o=a,W3(this),xCa(this,a),T3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.iK=function(){if(this.D){H3(this.context.logger,this.Y,4,X3(this).A.close);var a=g.vI();a&&this.M&&g.iI(a,this.M);U3(this)}};
g.h.uK=function(){g.T(this.G,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.fN=function(){var a=g.vI(),b=X3(this);b=b?b.D:this.K;a&&b&&q2(a,[b])};
g.h.eN=function(){var a=g.vI(),b=X3(this);b=b?b.D:this.K;a&&b&&r2(a,[b])};
g.h.iN=function(){var a=X3(this);I3(this.context.logger,8,a.C,a.A.WV);var b=g.vI();b&&a&&q2(b,[a.H,a.D])};
g.h.hN=function(){var a=g.vI(),b=X3(this);a&&b&&r2(a,[b.H])};
g.h.gN=function(a){var b=X3(this),c=g.vI();this.o?a?(a=this.context.logger,I3(a,9,b.C,b.A.Wx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.iI(c,b.H)):(a=this.context.logger,I3(a,12,b.C,b.A.Wx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.iI(c,b.D)):(a=this.context.logger,H3(a,this.Y,12,b.A.Wx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.K&&g.iI(c,this.K))};
var oCa={collaborator:QBa,donation:RBa,episode:A3,movie:A3,playlist:SBa,poll:TBa,productListing:VBa,simple:z3,tip:WBa,video:XBa};g.r(Y3,S3);Y3.prototype.Fr=function(){S3.prototype.Fr.call(this);yCa(this)};
Y3.prototype.show=function(){S3.prototype.show.call(this);var a=g.vI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&q2(a,[g.eI(b.itct)])};
Y3.prototype.hide=function(){S3.prototype.hide.call(this);var a=g.vI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&r2(a,[g.eI(b.itct)])};g.r(Z3,Y3);g.h=Z3.prototype;g.h.OV=function(a,b,c,d){this.C.stop();if(!this.B){var e=g.gi(a);this.o||(g.ei(a,e.width),g.ei(b,e.width));g.Oh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Oh(c,"right","1px");this.B=!0;g.L(a,!0);this.D=new g.V(function(){g.S(this.ra(),"iv-branding-active")},0,this);
this.D.start()}};
g.h.VL=function(a,b){g.Br(this.ra(),"iv-branding-active");this.F=new g.V((0,g.z)(function(){g.L(a,!1);this.o||g.ei(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){Y3.prototype.show.call(this);if(!this.G){g.S(this.ra(),"iv-branding");var a=this.annotation.data;this.H=a.image_width;this.A=g.he("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.L(this.A,!1);var b=g.he("DIV","branding-img-container",this.A);this.ra().appendChild(b);var c=g.he("DIV","iv-branding-context-name");g.xe(c,a.channel_name);var d=g.he("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=
new g.y_(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.o),this.o.A(d);b=g.he("DIV","iv-branding-context-subscribe-caret");c=g.he("DIV","branding-context-container-inner",b,c,d);g.L(c,!1);d=g.he("DIV","branding-context-container-outer",c);g.Oh(d,"right",this.H+"px");this.ra().appendChild(d);var e=this.annotation.Xa();e&&this.jl(this.A,e,this.annotation.id,a.session_data,
this.annotation.o);this.C=new g.V(g.Na(this.VL,c,d),500,this);g.K(this,this.C);this.context.A.X(this.ra(),"mouseover",(0,g.z)(this.OV,this,c,d,b,a.image_height));this.context.A.X(this.ra(),"mouseout",(0,g.z)(this.C.start,this.C,void 0));this.G=!0}E3(this.context.logger,this.annotation.o);g.L(this.ra(),!0);this.isActive=!0;if(this.A){a=this.A;var f=void 0===f?0:f;b=g.hi(a).width;c=g.Ba(void 0)?void 0:b;g.Vh(a,c);f=new p2(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,oAa);g.K(this,f);this.context.B.X(f,
"begin",g.Na(g.L,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(Y3.prototype.hide.call(this),g.L(this.ra(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);Y3.prototype.destroy.call(this)};g.r($3,Y3);g.h=$3.prototype;g.h.show=function(){this.isActive||(Y3.prototype.show.call(this),this.K||(zCa(this),this.K=!0),g.L(this.ra(),!0),this.annotation&&this.annotation.o&&E3(this.context.logger,this.annotation.o),g.Ug(function(){g.Br(this.ra(),"iv-promo-inactive")},100,this),this.ra().removeAttribute("aria-hidden"),this.isActive=!0,a4(this),BCa(this),CCa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.S(this.ra(),"iv-promo-inactive"),this.isActive=!1,this.ra().setAttribute("aria-hidden",!0))};
g.h.hq=function(a,b,c,d,e,f,k){return this.D?!1:Y3.prototype.hq.call(this,a,b,c,d,e,f,k)};
g.h.Ku=function(a,b){b.stopPropagation();BCa(this);CCa(this,a);this.o.focus()};
g.h.tL=function(a){this.J=!0;this.Ku(500,a)};
g.h.sL=function(){this.J=!1;ACa(this)};
g.h.xO=function(a){a.stopPropagation();this.hide();G3(this.context.logger,this.annotation.o)};
g.h.iL=function(a){a.stopPropagation();a4(this);this.D=!0;g.S(this.ra(),"iv-promo-collapsed-no-delay");this.F.start();G3(this.context.logger,this.annotation.o)};
g.h.destroy=function(){this.F.dispose();Y3.prototype.destroy.call(this)};g.r(b4,g.lV);g.h=b4.prototype;g.h.Gc=function(a,b){if(!ECa(g.Y(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.lt(b);c&&d4(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(qCa(this.o,b),i2(this.player)),!0}return null};
g.h.getOptions=function(){return ECa(g.Y(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Tw=function(){if(this.B){var a=g.PU(this.player).getVideoContentRect(!0);g.fi(this.B.element,a.width,a.height);g.Vh(this.B.element,a.left,a.top)}if(this.o){var b=g.WU(this.player);a=this.o;b=b.width;g.T(a.G,"iv-drawer-small",426>=b);g.T(a.G,"iv-drawer-big",1280<=b)}};
g.h.RS=function(a){this.Nc(a.state);g.X(a.state,2)&&(this.ce()&&this.se()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.dl(!1))};
g.h.load=function(){g.lV.prototype.load.call(this);this.Nc(g.OU(this.player));this.J++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.z)(this.vR,this,b,this.J),d=(0,g.z)(function(){this.F=null},this);
g.PH()&&(c=LCa(this,c));c={format:"XML",Hd:c,onError:d,bd:{}};a.isPharma&&(c.bd.pharma="1");c.method="POST";c.withCredentials=!0;d=g.Y(this.player);"gaming"==d.playerStyle&&(c.bd.gaming="1");(b=d.J.get(b))&&MCa(c,b);b=b&&(b.pi||b.Lt);if(!a.Io||b)a.re?FCa(this,a.re,c):(this.C=(0,g.z)(this.FN,this,c),this.player.addEventListener("videodatachange",this.C));g.cV(this.player,this.B.element,4);this.Tw()};
g.h.Nc=function(a){a=!a.isCued()&&!g.X(a,1024);g.kQ(this.D,a);g.kQ(this.B,a)};
g.h.FN=function(a){var b=this.player.getVideoData();b.re&&(this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null),FCa(this,b.re,a))};
g.h.unload=function(){ZBa(this.kb);g.aV(this.player,"annotations_module");g.Mb(this.A,function(a){a.destroy()});
g.Mb(this.L,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,i2(this.player));this.K=!1;this.F&&(this.F.abort(),this.F=null);this.A={};this.L={};this.D.hide();g.lV.prototype.unload.call(this);g.jQ(this.B);this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null)};
g.h.vR=function(a,b,c){this.F=null;if(!HCa(this,b,a)&&(a=g.PF(c)&&c.responseXML?c.responseXML:null)){d4(this,a);g.S(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.A){b=this.A[d].annotation;if(b.segment)if(c=b.segment,c.o.length)if(c=c.o[0].A||c.o[0].o||c.o[0].C,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.B,f.visible=!0);b=new g.lR(c,e,f);a.push(b)}}g.YU(this.player,a)}};
g.h.hF=function(a){a==this.player.getVideoData().videoId&&(this.loaded?NCa(this):this.load())};
g.h.CN=function(a){a=a.getId();var b=this.A[a];b&&!b.C&&(b=b.annotation,QCa(this,a),E3(this.kb,b.o))};
g.h.DN=function(a){e4(this,a.getId())};
g.h.fC=function(a){a&&(a.hide(),f4(this,"shown",!1,a.annotation.id),this.jp(a.annotation,"hidden"))};
g.h.nG=function(a){a&&(a.show(),f4(this,"shown",!0,a.annotation.id),this.jp(a.annotation,"shown"))};
g.h.nU=function(a,b,c){var d=this.A[a];if(d&&b.value!=c){b.value=c;var e=!1;uBa(d.annotation,function(a){e=e||a.value});
RCa(this,a,b,e)}};
g.h.nQ=function(a){if(a&&a.id){var b=a.Xa();if(b){var c=$2(b);if(c){var d=(0,g.z)(this.jp,this,a,"click");if("new"==R3(c,b.target)||SCa(this,b))d(),d=null;F3(this.kb,a.o,d)}}}};
g.h.jp=function(a,b){sBa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!SCa(this,c.url))){e=kCa(c.url);var f=jCa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=c4(this).o,g.M0(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&c4(this).o.Kc()&&c4(this).o.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.Y(this.player),(d=$2(c.url))?(f=iCa(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Na(lCa,e.pageId,e.Tc),d=new g.Hn(d),g.Ln(d,e(d.C)),d=d.toString())):
d=null,d&&(this.player.pauseVideo(),c=R3(d,c.url.target),e=a.itct,"ei"in g.DF(d)&&(d=g.uh(d,"ei")),g.tV(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.ER=function(){f4(this,"playerControlShow",!1)};
g.h.LT=function(){f4(this,"playerControlShow",!0)};
g.h.EN=function(a){f4(this,"rollOver",!0,a.id)};
g.h.Uh=function(a){f4(this,"rollOver",!1,a.id)};
g.h.TQ=function(a){a&&a.id&&(this.A[a.id].C=!0,e4(this,a.id),G3(this.kb,a.o),this.jp(a,"close"),f4(this,"closed",!0,a.id))};
g.h.ce=function(){return!!this.o&&this.o.isAvailable()};
g.h.se=function(){this.ce();return!!this.o&&this.o.D};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ce();this.o&&(a?c?T3(this.o,c,b):T3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):U3(this.o))};
g.h.dl=function(a,b){this.player.U(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.W=function(){g.Y(this.player).J.unsubscribe("vast_info_card_add",this.hF,this);g.Br(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.QH(a[b]);this.M.length=0;g.lV.prototype.W.call(this)};g.WZ.annotations_module=b4;g.WZ.creatorendscreen=J2;})(_yt_player);
