(function(g){var window=this;var QDa=function(a,b,c){a.o.has(b);a.o.add(b);g.Ef(c,function(){g.Txa(a,b)})},j5=function(a,b,c){var d=b.Aa();
g.T(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.gd(c?c:"mqdefault.jpg");var f=b instanceof g.AP&&b.lengthSeconds?g.LV(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.oR(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.AP?b.Da:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Ql||g.wV("\u89c2\u770b\u300a$TITLE\u300b",{TITLE:b.title}),duration:f,url:b.Hm(),is_live:l,is_list:k,is_mix:e,background:c?
"background-image: url("+c+")":""};b instanceof g.qR&&(d.playlist_length=b.getLength());a.update(d)},k5=function(a,b){g.lQ.call(this,{I:"div",
da:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},l5=function(a){g.W.call(this,{I:"div",
da:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},P:[{I:"div",N:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{I:"span",N:"ytp-upnext-top",P:[{I:"span",N:"ytp-upnext-header",ca:"\u63a5\u4e0b\u6765\u64ad\u653e"},{I:"span",N:"ytp-upnext-title",ca:"{{title}}"},{I:"span",N:"ytp-upnext-author",ca:"{{author}}"}]},{I:"a",N:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"\u64ad\u653e\u4e0b\u4e00\u4e2a\u89c6\u9891"},P:[{I:"svg",T:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},P:[{I:"circle",N:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",N:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",N:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",N:"ytp-upnext-bottom",P:[{I:"span",N:"ytp-upnext-cancel"},
{I:"span",N:"ytp-upnext-paused",ca:"\u81ea\u52a8\u64ad\u653e\u529f\u80fd\u5df2\u6682\u505c"}]}]});this.G=null;var b=this.o["ytp-upnext-cancel"];this.G=new g.W({I:"button",da:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"\u53d6\u6d88\u81ea\u52a8\u64ad\u653e"},ca:"\u53d6\u6d88"});g.K(this,this.G);this.G.X("click",this.FQ,this);this.G.A(b);this.B=a;this.M=this.o["ytp-svg-autoplay-ring"];this.J=this.H=this.D=this.F=null;this.K=new g.V(this.Wo,5E3,this);g.K(this,this.K);this.L=
0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.JS);this.sE();this.R(a,"autonavvisibility",this.sE);this.R(a,"mdxnowautoplaying",this.YR);this.R(a,"mdxautoplaycanceled",this.ZR);this.R(a,"mdxautoplayupnext",this.SG);3==this.B.getPresentingPlayerType()&&(a=(a=g.QU(g.LU(this.B)))?a.UK():null)&&this.SG(a)},m5=function(a,b){if(!a.D){g.qF("a11y-announce","\u63a5\u4e0b\u6765\u64ad\u653e "+a.F.title);
a.L=g.GH();a.D=new g.V((0,g.z)(a.vt,a,b),25);a.vt(b);var c=b||g.Y(a.B).experiments.A("autoplay_time")||1E4;a.B.Ba("onAutonavCoundownStarted",c)}g.Br(a.element,"ytp-upnext-autoplay-paused")},o5=function(a){n5(a);
a.L=g.GH();a.vt();g.S(a.element,"ytp-upnext-autoplay-paused")},n5=function(a){a.D&&(a.D.dispose(),a.D=null)},p5=function(a,b){b=void 0===b?!1:b;
if(g.Y(a.B).experiments.o("autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.F.Aa(),a.Wo(),a.H=new Notification("\u63a5\u4e0b\u6765\u64ad\u653e",{body:c.title,icon:c.gd()}),a.J=a.R(a.H,"click",a.AS),a.K.start())}n5(a);a.B.nextVideo(!1,b)},RDa=function(a){k5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.B=new g.W({I:"div",N:"ytp-subscribe-card",P:[{I:"img",N:"ytp-author-image",T:{src:b.Rk}},{I:"div",N:"ytp-subscribe-card-right",P:[{I:"div",N:"ytp-author-name",ca:b.author},{I:"div",N:"html5-subscribe-button-container"}]}]});g.K(this,this.B);this.B.A(this.element);this.D=new g.y_("\u8ba2\u9605",null,"\u9000\u8ba2",null,!0,!1,b.vl,b.subscribed,"trailer-endscreen",null,null,a);g.K(this,this.D);this.D.A(this.B.o["html5-subscribe-button-container"]);this.hide()},q5=function(a){var b=
g.Y(a),c=g.ZL||g.Jf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.A&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",da:e,T:{href:"{{url}}",target:d?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",N:"ytp-videowall-still-image",T:{style:"{{background}}"}},{I:"span",N:"ytp-videowall-still-info",P:[{I:"span",N:"ytp-videowall-still-info-bg",P:[{I:"span",N:"ytp-videowall-still-info-content",T:c,P:[{I:"span",N:"ytp-videowall-still-info-title",ca:"{{title}}"},{I:"span",N:"ytp-videowall-still-info-author",
ca:"{{author_and_views}}"},{I:"span",N:"ytp-videowall-still-info-live",ca:"\u76f4\u64ad"},{I:"span",N:"ytp-videowall-still-info-duration",ca:"{{duration}}"}]}]}]},{I:"span",da:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",N:"ytp-videowall-still-listlabel-icon"},"\u64ad\u653e\u5217\u8868",{I:"span",N:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",ca:"{{playlist_length}}"},")"]}]},{I:"span",da:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
P:[{I:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"\u89c6\u9891\u5408\u8f91",{I:"span",N:"ytp-videowall-still-listlabel-length",ca:" (50+)"}]}]});this.G=d;this.B=a;this.D=null;this.F=new g.jH(this);g.K(this,this.F);this.X("click",this.J);this.X("keypress",this.K);this.F.R(a,"videodatachange",this.H);g.Y(a).ia&&QDa(a.app.ka,this.element,this);this.H()},r5=function(a){k5.call(this,a,"videowall-endscreen");
this.L=a;this.H=0;this.D=[];this.J=this.F=this.G=null;this.K=this.aa=!1;this.Y=null;this.Z=new g.jH(this);g.K(this,this.Z);this.M=new g.V(g.Na(g.S,this.element,"ytp-show-tiles"),0);g.K(this,this.M);var b=new g.W({I:"button",da:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"\u4e0a\u4e00\u4e2a"},P:[g.EV()]});g.K(this,b);b.A(this.element);b.X("click",this.uO,this);this.O=new g.gQ({I:"div",N:"ytp-endscreen-content"});g.K(this,this.O);this.O.A(this.element);b=new g.W({I:"button",da:["ytp-button",
"ytp-endscreen-next"],T:{"aria-label":"\u4e0b\u4e00\u4e2a"},P:[g.FV()]});g.K(this,b);b.A(this.element);b.X("click",this.tO,this);this.B=new l5(a);g.K(this,this.B);g.cV(this.player,this.B.element,4);this.hide()},s5=function(a){return g.eV(a.player)&&a.lA()&&!a.J},SDa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.XV(g.Y(a.L),b);
g.K(a,b);return b})},t5=function(a){var b=a.ag();
b!=a.aa&&(a.aa=b,a.player.U("autonavvisibility"))},u5=function(a){g.lV.call(this,a);
this.o=null;this.A=new g.jH(this);g.K(this,this.A);this.C=g.Y(a);TDa(a)?this.o=new r5(this.player):this.C.La?this.o=new RDa(this.player):this.o=new k5(this.player);g.K(this,this.o);g.cV(this.player,this.o.element,4);this.LF();this.A.R(a,"videodatachange",this.LF,this);this.A.R(a,g.nR("endscreen"),this.IN,this);this.A.R(a,"crx_endscreen",this.JN,this)},TDa=function(a){a=g.Y(a);
return a.Ia&&!a.La};
g.r(k5,g.lQ);k5.prototype.create=function(){this.created=!0};
k5.prototype.destroy=function(){this.created=!1};
k5.prototype.lA=function(){return!1};
k5.prototype.ag=function(){return!1};g.r(l5,g.W);g.h=l5.prototype;g.h.Wo=function(){this.H&&(this.K.stop(),this.Ka(this.J),this.J=null,this.H.close(),this.H=null)};
g.h.sE=function(){g.kQ(this,this.B.ag())};
g.h.AS=function(){window.focus();this.Wo()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.vt=function(a){a=a||g.Y(this.B).experiments.A("autoplay_time")||1E4;var b=Math.min(g.GH()-this.L,a);a=Math.min(b/a,1);this.M.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.B.getPresentingPlayerType()?p5(this,!0):this.D&&this.D.start()};
g.h.JS=function(a){!g.ve(this.G.element,g.YG(a))&&g.ZV(a,this.B)&&p5(this)};
g.h.FQ=function(){g.NU(this.B,!0)};
g.h.YR=function(a){this.B.getPresentingPlayerType();this.show();m5(this,a)};
g.h.SG=function(a){this.B.getPresentingPlayerType();this.F&&this.F.Aa().videoId==a.Aa().videoId||(this.F=a,j5(this,a,"hqdefault.jpg"))};
g.h.ZR=function(){this.B.getPresentingPlayerType();n5(this);this.hide()};
g.h.W=function(){n5(this);this.Wo();g.W.prototype.W.call(this)};g.r(RDa,k5);g.r(q5,g.W);q5.prototype.Yk=function(){g.gV(this.B,this.element);var a=this.D.Aa().videoId,b=this.D.getPlaylistId();g.M0(this.B.app,a,this.D.Jd,b,void 0,void 0,void 0)};
q5.prototype.J=function(a){g.ZV(a,this.B,this.G,this.D.Jd||void 0)&&this.Yk()};
q5.prototype.K=function(a){switch(a.keyCode){case 13:case 32:g.cH(a)||(this.Yk(),g.bH(a))}};
q5.prototype.H=function(){var a=this.B.getVideoData(),b=g.Y(this.B);this.G=a.Jc?!1:b.o};g.r(r5,k5);g.h=r5.prototype;g.h.create=function(){k5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.G=SDa(this,a),this.F=a);this.Vg();this.Z.R(this.player,"appresize",this.Vg);this.Z.R(this.player,"onVideoAreaChange",this.Vg);this.Z.R(this.player,"videodatachange",this.vO);this.Z.R(this.player,"autonavchange",this.kw);this.Z.R(this.player,"autonavcancel",this.sO);a=this.F.autonavState;a!=this.Y&&this.kw(a);this.Z.R(this.element,"transitionend",this.jU)};
g.h.destroy=function(){g.lH(this.Z);g.Gf(this.D);this.D=[];this.G=null;k5.prototype.destroy.call(this);g.Br(this.element,"ytp-show-tiles");this.M.stop();this.Y=this.F.autonavState};
g.h.lA=function(){return 1!=this.F.autonavState};
g.h.show=function(){k5.prototype.show.call(this);g.Br(this.element,"ytp-show-tiles");g.Y(this.player).A?g.rv(this.M):this.M.start();(this.K||this.J&&this.J!=this.F.clientPlaybackNonce)&&g.NU(this.player,!1);s5(this)?(t5(this),2==this.F.autonavState?g.Y(this.player).experiments.o("fast_autonav_in_background")&&3==this.player.getVisibilityState()?p5(this.B,!0):m5(this.B):3==this.F.autonavState&&o5(this.B)):(g.NU(this.player,!0),t5(this))};
g.h.hide=function(){k5.prototype.hide.call(this);o5(this.B);t5(this)};
g.h.jU=function(a){g.YG(a)==this.element&&this.Vg()};
g.h.Vg=function(){if(this.G&&this.G.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.WU(this.L,!0),b=g.wQ(this.L);b&&(b=b.Yc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.G.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,v=b<=f-2&&n>=t*m,A=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&A)n-=p*m,e+=2;else if(v)n-=t*m,b+=2;else if(A)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Hd(a.width/m||1,1,1.21);n*=g.Hd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.fi(a,m,n);g.Oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.B;f=this.G[0];c.F=f;j5(c,f,"hqdefault.jpg");g.T(this.element,"ytp-endscreen-takeover",s5(this));t5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-
2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),p=g.Jd(p+this.H,l),0!=t){v=this.D[c];v||(v=new q5(this.player),this.D[c]=v,a.appendChild(v.element));A=Math.floor(n*k/e);var E=Math.floor(m*f/b),G=Math.floor(n*(k+t)/e)-A-4,M=Math.floor(m*(f+t)/b)-E-4;g.Vh(v.element,E,A);g.fi(v.element,M,G);g.Oh(v.element,"transitionDelay",(k+f)/20+"s");g.T(v.element,"ytp-videowall-still-mini",1==t);g.T(v.element,"ytp-videowall-still-large",2<t);t=v;p=this.G[p];t.D!=p&&(t.D=p,j5(t,p,g.zr(t.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),v=(p=p.Jd)&&p.itct)&&(p=t.B,g.Y(p).ia&&(t=t.element,p.app.ka.o.has(t),v&&(t.visualElement=g.eI(v))));c++}g.T(this.element,"ytp-endscreen-paginate",c<l);for(b=this.D.length-1;b>=c;b--)e=this.D[b],g.pe(e.element),g.Ff(e);this.D.length=c}};
g.h.vO=function(){var a=this.player.getVideoData();this.F!=a&&(this.H=0,this.G=SDa(this,a),this.F=a,this.Vg())};
g.h.tO=function(){this.H+=this.D.length;this.Vg()};
g.h.uO=function(){this.H-=this.D.length;this.Vg()};
g.h.UM=function(){return!!this.B.D};
g.h.kw=function(a){1==a?(this.K=!1,this.J=this.F.clientPlaybackNonce,n5(this.B),this.C&&this.Vg()):(this.K=!0,this.C&&s5(this)&&(2==a?m5(this.B):3==a&&o5(this.B)))};
g.h.sO=function(a){if(a){for(a=0;a<this.D.length;a++)g.hV(this.L,this.D[a].element,!0);this.kw(1)}else this.J=null,this.K=!1;this.Vg()};
g.h.ag=function(){return this.C&&s5(this)};g.r(u5,g.lV);g.h=u5.prototype;g.h.Tn=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!TDa(this.player)||b;a=a.pd;var c=g.u0(this.player.app);return b&&!a&&!c};
g.h.ag=function(){return this.o.ag()};
g.h.QM=function(){return this.ag()?this.o.UM():!1};
g.h.W=function(){g.aV(this.player,"endscreen");g.lV.prototype.W.call(this)};
g.h.load=function(){g.lV.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.lV.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.IN=function(a){this.Tn()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.JN=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.LF=function(){g.aV(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.lR(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.K(this,a);var b=new g.lR(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.K(this,b);g.YU(this.player,[a,b])};g.WZ.endscreen=u5;})(_yt_player);
